### ISSUE TITLE
[GLPI 10 RC1] : Simplify interface no longer works correctly with this version for ticket management

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#10570]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10 RC1

### Bug description

Example :
Glpi 9.5.7 OK
![image](https://user-images.githubusercontent.com/68054991/152802921-a4be6ebc-a4c9-42e7-8317-79f368eb8531.png)

GLPi 10 RC1 : bug scree display KO
![image](https://user-images.githubusercontent.com/68054991/152803116-a42099ac-2a23-4457-b0e1-7070a24c175c.png)
nothing is displayed

Error message in the log

### Relevant log output

```shell
[2022-02-07 14:59:33] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Glpi\Application\View\Extension\ConfigExtension::getEntityConfig(): Argument #2 ($entity_id) must be of type int, null given, called in /var/www/html/glpi10beta/files/_cache/templates/17/174511734a315dcad8e51e2bcb10ae634f988192c04f41ccc9ee9b54908cc705.php on line 208 in /var/www/html/glpi10beta/src/Application/View/Extension/ConfigExtension.php at line 77
  Backtrace :
  ...b10ae634f988192c04f41ccc9ee9b54908cc705.php:208 Glpi\Application\View\Extension\ConfigExtension->getEntityConfig()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_19ba154cc12c09e9eaa4c53166a07b2d61b7b2a41a9462261cfebaa9bb4cc15c->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1321 Twig\TemplateWrapper->render()
  ...76a9d7c53209a0630e00b1a0832a95c2bd1e485.php:132 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_1f44da49026ccad05d04218ff542f3fedbd1892edf89c7e403be20cf6b37f142->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1321 Twig\TemplateWrapper->render()
  ...04ca8a5a35400832e0922318979d9f4fe806549.php:287 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_54a0249b309f83c5cd202392b3ad34cea92049160590b0430c57e3ab37700c7e->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  src/Ticket.php:4198                                Glpi\Application\View\TemplateRenderer->display()
  front/helpdesk.public.php:96                       Ticket->showFormHelpdesk()
```

### Page URL

/front/helpdesk.public.php

### Steps To reproduce

1 log with one user simplify
2 create ticket mode simplify interface

**Comment by steph461** [comment]
I delete the _cache.  I have same issue
if I want to create a ticket in simplified mode, it still creates the cache folders

delete ok
![image](https://user-images.githubusercontent.com/68054991/154099787-f5d15fbe-0bfa-4406-9908-8ac11fc5b907.png)

after
![image](https://user-images.githubusercontent.com/68054991/154099964-742bd38d-4976-4495-9065-6a7cccb0e40f.png)


log 15/02/2022

```shell
[2022-02-15 16:59:41] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Glpi\Application\View\Extension\ConfigExtension::getEntityConfig(): Argument #2 ($entity_id) must be of type int, null given, called in /var/www/html/glpi10beta/files/_cache/templates/17/174511734a315dcad8e51e2bcb10ae634f988192c04f41ccc9ee9b54908cc705.php on line 208 in /var/www/html/glpi10beta/src/Application/View/Extension/ConfigExtension.php at line 77
  Backtrace :
  ...b10ae634f988192c04f41ccc9ee9b54908cc705.php:208 Glpi\Application\View\Extension\ConfigExtension->getEntityConfig()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_19ba154cc12c09e9eaa4c53166a07b2d61b7b2a41a9462261cfebaa9bb4cc15c->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1321 Twig\TemplateWrapper->render()
  ...76a9d7c53209a0630e00b1a0832a95c2bd1e485.php:132 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_1f44da49026ccad05d04218ff542f3fedbd1892edf89c7e403be20cf6b37f142->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1321 Twig\TemplateWrapper->render()
  ...04ca8a5a35400832e0922318979d9f4fe806549.php:287 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_54a0249b309f83c5cd202392b3ad34cea92049160590b0430c57e3ab37700c7e->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  src/Ticket.php:4198                                Glpi\Application\View\TemplateRenderer->display()
  front/helpdesk.public.php:96                       Ticket->showFormHelpdesk()
```

**Comment by steph461** [comment]
_cache/templates/17/174511734a315dcad8e51e2bcb10ae634f988192c04f41ccc9ee9b54908cc705.php
f
older 17 :  file php
[17.zip](https://github.com/glpi-project/glpi/files/8072668/17.zip)

**Comment by cedric-anne** [comment]
So the issue seems to be that `item.fields['entities_id']` is not defined in `templates/components/itilobject/actors/main.html.twig`.

This template is called with many arguments in the simplified interface context (including `entities_id`), and is call without any argument in the "complete" interface context. I do not know which call is correct, so I do not know how to fix this, but I am pretty sure that as same template should always take its value from the same place.

**Comment by steph461** [comment]
If it helps, all _cache folders when creating the ticket.
Glpi create these folders when clicking
[folder_cache_ticket.zip](https://github.com/glpi-project/glpi/files/8078530/folder_cache_ticket.zip)

**Comment by steph461** [comment]
_Cache version 9.5.7 with same handling, Interface Ok
[_cache_version 9.5.7.zip](https://github.com/glpi-project/glpi/files/8079044/_cache_version.9.5.7.zip)
K

**Comment by jfumanat** [comment]
hello, the same thing happens to me, if this helps by hiding the whatcher field, the simple interface looks complete, it seems that this field generates the bug when showing it.

**Comment by jfumanat** [comment]
Hello

I found the error in line 77 of the file ConfigExtension.php the variable "$entity_id" has the type "int" prefixed when editing the file and removing the "int" from that variable and reloading apache the simple interface is shown complete. as seen in the picture before and after:

**Before:**
![image](https://user-images.githubusercontent.com/100037102/155321396-9f59ead5-4439-479c-8223-0ef7d3601e9d.png)
**After:**
![image](https://user-images.githubusercontent.com/100037102/155322828-254a7315-6a12-4fb2-83d6-70ebea44631c.png)

**Comment by cedric-anne** [comment]
> Hello
> 
> I found the error in line 77 of the file ConfigExtension.php the variable "$entity_id" has the type "int" prefixed when editing the file and removing the "int" from that variable and reloading apache the simple interface is shown complete. as seen in the picture before and after:
> 
> **Before:** ![image](https://user-images.githubusercontent.com/100037102/155321396-9f59ead5-4439-479c-8223-0ef7d3601e9d.png) **After:** ![image](https://user-images.githubusercontent.com/100037102/155322828-254a7315-6a12-4fb2-83d6-70ebea44631c.png)

It is intendeed to not accept null values here.

**Comment by cedric-anne** [comment]
@steph461 

Can you try to reproduce on GLPI 10.0.0-rc3 ?

**Comment by steph461** [comment]
@cedric-anne 

same issue with RC3

![image](https://user-images.githubusercontent.com/68054991/159681233-51660e0b-6200-426a-97e2-314b8d665205.png)
![image](https://user-images.githubusercontent.com/68054991/159681583-4d7d9ae6-2704-4b1f-a07b-558464bbfb78.png)



````shell
[2022-03-23 11:40:42] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Glpi\Application\View\Extension\ConfigExtension::getEntityConfig(): Argument #2 ($entity_id) must be of type int, null given, called in /var/www/html/glpi10beta/files/_cache/templates/9f/9ff583148473b082ebfcc9004f2cf43a514b2451dc47575b1505d650adcf0c31.php on line 208 in /var/www/html/glpi10beta/src/Application/View/Extension/ConfigExtension.php at line 77
  Backtrace :
  ...f2cf43a514b2451dc47575b1505d650adcf0c31.php:208 Glpi\Application\View\Extension\ConfigExtension->getEntityConfig()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_8257432682022c6565e0300b65c1627b74e39ba89c8b20840e445be7152c0767->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1323 Twig\TemplateWrapper->render()
  ...a6331e08d32cc3d5d28b4672ed653907d8461cb.php:132 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_5e9c5e31abcae7c45a94054a3dd84c186f72104bc8520eafd1c593f35b41074b->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1323 Twig\TemplateWrapper->render()
  ...472cedcee257a3b3322c323477ee2ad316607e8.php:288 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_a82d904ad3a598c1d22116c13bde64f53af04469ccb75c5e34a1a7f6448b6141->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  src/Ticket.php:4189                                Glpi\Application\View\TemplateRenderer->display()
  front/helpdesk.public.php:96                       Ticket->showFormHelpdesk()

**Comment by cedric-anne** [comment]
Are you able to reproduce easilly with a freshly installed database, or with a database upgraded from GLPI 9.x to GLPI 10.0.0-rc3 with no intermediate usage on GLPI 10.0.0-beta/rc1/rc2 ?

**Comment by steph461** [comment]
Gabarit ticket it always displayed correctly ( RC1, RC2)
![image](https://user-images.githubusercontent.com/68054991/159683246-00ae241d-bbfe-4938-8e9c-08d552b88af6.png)

**Comment by steph461** [comment]
> Are you able to reproduce easilly with a freshly installed database, or with a database upgraded from GLPI 9.x to GLPI 10.0.0-rc3 with no intermediate usage on GLPI 10.0.0-beta/rc1/rc2 ?

I migrated my base 9.5.7 to 10.rc3

**Comment by steph461** [comment]
> Hello
> 
> I found the error in line 77 of the file ConfigExtension.php the variable "$entity_id" has the type "int" prefixed when editing the file and removing the "int" from that variable and reloading apache the simple interface is shown complete. as seen in the picture before and after:
> 
> **Before:** ![image](https://user-images.githubusercontent.com/100037102/155321396-9f59ead5-4439-479c-8223-0ef7d3601e9d.png) **After:** ![image](https://user-images.githubusercontent.com/100037102/155322828-254a7315-6a12-4fb2-83d6-70ebea44631c.png)

If i do this handling , its OK

**Comment by cedric-anne** [comment]
> > Hello
> > I found the error in line 77 of the file ConfigExtension.php the variable "$entity_id" has the type "int" prefixed when editing the file and removing the "int" from that variable and reloading apache the simple interface is shown complete. as seen in the picture before and after:
> > **Before:** ![image](https://user-images.githubusercontent.com/100037102/155321396-9f59ead5-4439-479c-8223-0ef7d3601e9d.png) **After:** ![image](https://user-images.githubusercontent.com/100037102/155322828-254a7315-6a12-4fb2-83d6-70ebea44631c.png)
> 
> If i do this handling , its OK

This should not be done, as I said in a previous comment.

So, without this patch, is the issue still there ?

**Comment by steph461** [comment]
without this patch, I migrated the data 9.5.7 (23/03/2022) to 10.RC3, I still have the same problem

**Comment by johanumana** [comment]
Hello

I updated to version 10 RC3 from version RC2 and the error still continues, the form keeps disappearing, the error occurs when you enable the observer change in the simple form templates, when you put that field the form changes and stays alone with two options, if that field is removed it remains normal.
however this, note that if this is done with the selft-service profile it does not happen with the other profiles, even with profiles that are created new, I hope this can give more guidance.
As for the change I found, it no longer takes full effect, it enables the full form but does not allow writing in the observer field

**Comment by cedric-anne** [comment]
@steph461 @johanumana 

Could you test if #11308 solves your issue ?

**Comment by steph461** [comment]
same issue

````shell
[2022-04-19 12:19:21] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Glpi\Application\View\Extension\ConfigExtension::getEntityConfig(): Argument #2 ($entity_id) must be of type int, null given, called in /var/www/html/glpi10beta/files/_cache/templates/81/815ff2cdda1a179b3f4103fcdcc8e439af0d2f9aa3ab240dbc479998840b9bb1.php on line 208 in /var/www/html/glpi10beta/src/Application/View/Extension/ConfigExtension.php at line 77
  Backtrace :
  ...cc8e439af0d2f9aa3ab240dbc479998840b9bb1.php:208 Glpi\Application\View\Extension\ConfigExtension->getEntityConfig()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_cad52048ed337bb5fd265970d5564ebdeb5cfd59afc6ed05217e253a2d4a6f32->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1323 Twig\TemplateWrapper->render()
  ...a0456f2a5addc952aa9f253284fbcc91fd5cc2f.php:132 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_731df802caf67707b6af47fcddff338770789df65db1e65c7ed9b277a5119037->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1323 Twig\TemplateWrapper->render()
  ...6bfcbcdc74588235dbabffb5d208828f3ea5a86.php:288 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_06a054706ffbb65457409a6beef3aed900a0aecab9ef112c9fe7a366b18cda48->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  src/Ticket.php:4005                                Glpi\Application\View\TemplateRenderer->display()
  front/helpdesk.public.php:96                       Ticket->showFormHelpdesk()

**Comment by johanumana** [comment]
Hello
I updated to version 10 final, I did the tests but the same thing happens if I add the observer field to the simple form, only the two options appear, there is no change, if I change the variable that I mentioned before, the complete form appears but it does not allow me to write anything in the observing field.

![image](https://user-images.githubusercontent.com/19317630/164707444-0f9cbfca-3a70-46dd-9cca-a51690656a21.png)
![image](https://user-images.githubusercontent.com/19317630/164707541-66bbf303-ff9f-4b50-a9ee-b1f7fc409087.png)

I created some additional profiles that I need to have with these, the error appears, with the only profile that works correctly is with self-service.

**Comment by cedric-anne** [comment]
Hi,

Could you try to reproduce on a GLPI 10.0.0 installed from scratch (i.e. without importing a database backup). In this case, could you provide a dump of this database, so we could try to reproduce on our side ?

**Comment by steph461** [comment]
@cedric-anne 
I trie, its same issue

**Comment by johanumana** [comment]
hello

If I could, let me do a lab here with the clean version, I'll do tests and tell you if the failure occurs, it will take me a while but I'll let you know as soon as I have results.

To complement I migrated from glpi 9.5.7 to glpi 10 and the implementation originally comes from glpi 9.2 from there I have been migrating towards stable versions up to 10.

**Comment by johanumana** [comment]
Hello

I have already done the lab, set up a test virtual machine, install clean glpi 10 and replicate the situation and exactly the same thing happens, the form is incomplete when the observer field is added.
what I did was leave the root entity alone, create a user and an additional profile which is what I need and assign the simple form to the profile, leave the observer field activated and the same thing happens.
If I do the exercise with the self-service user, it works fine.
[glpi.zip](https://github.com/glpi-project/glpi/files/8582388/glpi.zip)

attached database
![image](https://user-images.githubusercontent.com/19317630/165750599-5990f7cc-6d86-4b6c-b67e-1c54e9eacf05.png)

**Comment by Benbenas** [comment]
Hello
I have the same issue after upgrading from 9.5.6 to the last stable version 10.0 : Category is empty, only the type, category and urgency fields are displayed and the create button is missing. This issue also occurred on standard interface but I solved it by removing the field "impact" in the "predefined field". It is properly displayed in the template view.

attached debug message
simplified interface
![simpl-debugmsg](https://user-images.githubusercontent.com/104769252/166233243-6da43701-225e-48c3-9256-21f32699c285.jpg)
standard interface
![std-debugmsg](https://user-images.githubusercontent.com/104769252/166233246-d0afe2a9-9000-4d3c-8111-33fe9e272364.jpg)

Unfortunately, I cannot give you more information because I rolled it back to 9.5.6 because it is in prod environment.

**Comment by cconard96** [comment]
I was able to recreate the originally reported issue by trying to copy the profile settings from the provided SQL dump.

**Comment by cconard96** [comment]
This should be fixed by #11583.

If you have this issue and still have access to a GLPI 10 instance, could you please test it to help verify this issue is fixed completely?

**Comment by steph461** [comment]
its good for me fix OK

**Comment by johanumana** [comment]
Hello

I updated to 10.01 and have done tests, but the error still persists

**Comment by cconard96** [comment]
The proposed fix hasn't been merged yet so it won't be included in the nighlty version (there is no finalized 10.0.1 release yet). The changes need to be applied manually (see the files changed tab of the pull request).

**Comment by johanumana** [comment]
Hello

I have already changed the variable as you mention in the ConfigExtension.php file, when you change it the observer field appears but it is not editable, if you add a category the observer field disappears, so it is not the complete solution, something else is needed.

**Comment by cedric-anne** [comment]
@johanumana 

Please open another issue. The initial problem has been solved, so I close the issue.

**Comment by johanumana** [comment]
Hello

The original issue not solved, the original reportet issue continue

**Comment by cconard96** [comment]
Please test with the latest nightly or wait for the 10.0.1 release.
The original poster has validated the fix so if you still have the issue with the original code + the fix, it seems like it would be some other issue that should be tracked in another issue report.
