### ISSUE TITLE
[GLPI 10.0.0-rc1] ITIL Category not visible

### ISSUE THREAD

**Issue by atomiksteak77** [glpi-project/glpi#10591]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0RC1

### Bug description

[French]

Bonjour,

Impossible de voir mes catégories ITIL existantes en interface simplifiée , elles sont visibles en interface standard 
Test effectués avec le même utilisateur ayant les Droits super-Admin et Self-Service.

Visible en super Admin , interface standard
Non visible en self-service , interface simplifiée
Visible en self-sevice , interface standard

[ English]

Hello,

I can't see my existing ITIL categories in simplified interface, they are visible in standard interface
Test done with the same user having the super-Admin and Self-Service rights.

Visible in super Admin , standard interface
Not visible in self-service, simplified interface
Visible in self-service, standard interface

![image](https://user-images.githubusercontent.com/99338821/153211605-3efd5324-4ca9-4f4c-8adb-c4fc3a305bcb.png)
![image](https://user-images.githubusercontent.com/99338821/153211645-56f6d8f3-a658-48b1-b8af-46dccdb2a6c1.png)

### Steps To reproduce

Log on as glpi
Access Setup > Dropdown
Create an Itil Categories if not exist
Verify in a ticket with standard interface and with the simplified interface

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0-rc1 ( => /var/www/glpi_log_prod)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux SRV-GLPI 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64
PHP 8.0.15 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.43 (Ubuntu) (Apache/2.4.43 (Ubuntu) Server at assistancelogistique Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.4.8-MariaDB-1:10.4.8+maria~bionic
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi_log_prod
	Host info: Localhost via UNIX socket
	
PHP version (8.0.15) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (10.4.8) is supported.
The log file has been created successfully.
Write access to /var/www/glpi_log_prod/files/_cache has been validated.
Write access to /var/www/glpi_log_prod/config has been validated.
Write access to /var/www/glpi_log_prod/files/_cron has been validated.
Write access to /var/www/glpi_log_prod/files has been validated.
Write access to /var/www/glpi_log_prod/files/_dumps has been validated.
Write access to /var/www/glpi_log_prod/files/_graphs has been validated.
Write access to /var/www/glpi_log_prod/files/_lock has been validated.
Write access to /var/www/glpi_log_prod/files/_pictures has been validated.
Write access to /var/www/glpi_log_prod/files/_plugins has been validated.
Write access to /var/www/glpi_log_prod/files/_rss has been validated.
Write access to /var/www/glpi_log_prod/files/_sessions has been validated.
Write access to /var/www/glpi_log_prod/files/_tmp has been validated.
Write access to /var/www/glpi_log_prod/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
The directory could not be created in /var/www/glpi_log_prod/marketplace.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/glpi_log_prod
GLPI_CONFIG_DIR: /var/www/glpi_log_prod/config
GLPI_VAR_DIR: /var/www/glpi_log_prod/files
GLPI_MARKETPLACE_DIR: /var/www/glpi_log_prod/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/glpi_log_prod/files
GLPI_CACHE_DIR: /var/www/glpi_log_prod/files/_cache
GLPI_CRON_DIR: /var/www/glpi_log_prod/files/_cron
GLPI_DUMP_DIR: /var/www/glpi_log_prod/files/_dumps
GLPI_GRAPH_DIR: /var/www/glpi_log_prod/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/glpi_log_prod/files/_locales
GLPI_LOCK_DIR: /var/www/glpi_log_prod/files/_lock
GLPI_LOG_DIR: /var/www/glpi_log_prod/files/_log
GLPI_PICTURE_DIR: /var/www/glpi_log_prod/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/glpi_log_prod/files/_plugins
GLPI_RSS_DIR: /var/www/glpi_log_prod/files/_rss
GLPI_SESSION_DIR: /var/www/glpi_log_prod/files/_sessions
GLPI_TMP_DIR: /var/www/glpi_log_prod/files/_tmp
GLPI_UPLOAD_DIR: /var/www/glpi_log_prod/files/_uploads
GLPI_INVENTORY_DIR: /var/www/glpi_log_prod/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi_log_prod/locales
GLPI_VERSION: 10.0.0-rc1
GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/glpi_log_prod/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.3 in (/var/www/glpi_log_prod/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi_log_prod/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/glpi_log_prod/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/glpi_log_prod/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi_log_prod/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi_log_prod/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi_log_prod/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi_log_prod/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi_log_prod/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi_log_prod/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi_log_prod/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi_log_prod/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi_log_prod/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi_log_prod/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi_log_prod/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi_log_prod/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi_log_prod/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi_log_prod/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi_log_prod/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi_log_prod/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi_log_prod/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi_log_prod/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi_log_prod/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi_log_prod/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi_log_prod/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi_log_prod/vendor/psr/cache/src)
league/csv in (/var/www/glpi_log_prod/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi_log_prod/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi_log_prod/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi_log_prod/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi_log_prod/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi_log_prod/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi_log_prod/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi_log_prod/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi_log_prod/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/glpi_log_prod/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi_log_prod/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi_log_prod/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found

</details><details>

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@smtp.local)

</details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.13.0-alpha.3 State: Enabled

</pre></details>

**Comment by cconard96** [comment]
Can you verify this issue was resolved for you by #10617? You should check that the categories have the option to be visible in the simplified interface enabled too.

**Comment by atomiksteak77** [comment]
Hello,

I still reproduce the incident on this migrated installation.
On a new installation no worries.
However, I have the evolution of the field YES / NO in the drop-down menu to display "Visible in the simplified interface".


Best regards

**Comment by atomiksteak77** [comment]
![image](https://user-images.githubusercontent.com/99338821/154104996-c6e9fc86-35f8-41b8-9891-101f0493520b.png)

**Comment by cedric-anne** [comment]
I close this issue due to lack of feedback. Feel free to reopen.

**Comment by WebGregGit** [comment]
Hi @cedric-anne 

After upgrading from 9.5.6 to 10 rc3 I have the same problem. `is_helpdeskvisible` is set to 1.

I have problem only with simplified interface - standard is OK.

And if I'm on an account with the permission to edit the ticket templates - the preview of the simplified interface also works ok.

**Comment by DZbox** [comment]
> Hi @cedric-anne
> 
> After upgrading from 9.5.6 to 10 rc3 I have the same problem. `is_helpdeskvisible` is set to 1.
> 
> I have problem only with simplified interface - standard is OK.
> 
> And if I'm on an account with the permission to edit the ticket templates - the preview of the simplified interface also works ok.

The same issue at v.10.0.0 after upgrade from 9.5.2. Only using simplified interface. Settings are looking fine

**Comment by atomiksteak77** [comment]
> Are these categories visible in the entity context of your simplified interface ?

Hello,

I'm not sure I understand the question, I only have one entity in my GLPI (root entity)

**Comment by atomiksteak77** [comment]
With the standard interface
![image](https://user-images.githubusercontent.com/99338821/165967214-fb1caf76-d69a-480b-a8be-6b9c24dc1e1f.png)

![image](https://user-images.githubusercontent.com/99338821/165967246-0da62e92-faef-4cd3-93a6-1db34f769887.png)

With Simplified interface : 

![image](https://user-images.githubusercontent.com/99338821/165967392-411f61e5-1eea-423f-bf27-2e91f5f4231a.png)
![image](https://user-images.githubusercontent.com/99338821/165967422-74e42818-d577-46cf-a958-5a41de292b20.png)

**Comment by Serpher1** [comment]
> > Hi @cedric-anne
> > After upgrading from 9.5.6 to 10 rc3 I have the same problem. `is_helpdeskvisible` is set to 1.
> > I have problem only with simplified interface - standard is OK.
> > And if I'm on an account with the permission to edit the ticket templates - the preview of the simplified interface also works ok.
> 
> The same issue at v.10.0.0 after upgrade from 9.5.2. Only using simplified interface. Settings are looking fine. #10570 helped me. I have changed line 77 of the file ConfigExtension.php - removed int for "$entity_id"

THIS. Removing int helped big time!

**Comment by cedric-anne** [comment]
> > > Hi @cedric-anne
> > > After upgrading from 9.5.6 to 10 rc3 I have the same problem. `is_helpdeskvisible` is set to 1.
> > > I have problem only with simplified interface - standard is OK.
> > > And if I'm on an account with the permission to edit the ticket templates - the preview of the simplified interface also works ok.
> > 
> > 
> > The same issue at v.10.0.0 after upgrade from 9.5.2. Only using simplified interface. Settings are looking fine. #10570 helped me. I have changed line 77 of the file ConfigExtension.php - removed int for "$entity_id"
> 
> THIS. Removing int helped big time!

Maybe, but `$entity_id` should not be null here. If you allow null values to pass here, then form will consider that your are on root entity, and entity visibility restriction / entity configuration will not be applied. So we have to find source of the issue, and fix it, but we are still not able to reproduce.

**Comment by cconard96** [comment]
Please test #11583 as the entity issue should be fixed by it. If you removed the `int` type constraint in the ConfigExtension file, please re-add it before testing the fix.

**Comment by Serpher1** [comment]
@cconard96 
I have tested the #11583 and can confirm that it fixed the issue.
I've reverted changes in ConfigExtension.php and changed lines in .twig files.
Upgraded from 9.5.6 to v10 main release.

**Comment by DZbox** [comment]
> Please test #11583 as the entity issue should be fixed by it. If you removed the `int` type constraint in the ConfigExtension file, please re-add it before testing the fix.

Works for me also, thank you!
