### ISSUE TITLE
cant see global kanban in read-only

### ISSUE THREAD

**Issue by Lanoixdecoco** [glpi-project/glpi#12672]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.2

### Bug description

Context : I have a read-only user for projects and global kanban
bug : when he try to see global kanban, it show nothing :
![image](https://user-images.githubusercontent.com/55001492/190663005-0cc2b607-d47b-4515-b7fc-2c4bff68600c.png)

This is the user profile : 
![image](https://user-images.githubusercontent.com/55001492/190659657-de40b114-253b-4bb2-8aef-3d4603b3da6f.png)

It cant see global kanban without theses two roles : 'create' and 'update' projects, and that's not Read-only anymore
![image](https://user-images.githubusercontent.com/55001492/190659934-7e1e6211-640d-4ca3-ac59-059a4d9af4ac.png)

expected behaviour : 'See all' show global kanban for the user, without create/update

### Steps To reproduce

With admin account : 
1.create a user
2.create a profile like this ![image](https://user-images.githubusercontent.com/55001492/190659657-de40b114-253b-4bb2-8aef-3d4603b3da6f.png)
3.associate user with profil
4.create a project
5.create task with any state

6.log with the new user 
7..check global kanban

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.2 (/GLPI => /homepages/35/d215549132/htdocs/GLPI)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
PHP 7.4.30 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date, dba, dom,
	exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sodium, sqlite3, standard, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl,
	zip, zlib)
Setup: max_execution_time="50000" memory_limit="-1" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="64M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.115 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.5.17-MariaDB-1:10.5.17+maria~deb11-log
	Server SQL Mode: 
	Parameters: dbu2455766@db5010116255.hosting-data.io/dbs8574761
	Host info: db5010116255.hosting-data.io via TCP/IP
	
PHP version (7.4.30) is supported.
Sessions configuration is OK.
Allocated memory is unlimited.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.17) is supported.
The log file has been created successfully.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_cache has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/config has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_cron has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_dumps has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_graphs has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_lock has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_pictures has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_plugins has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_rss has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_sessions has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_tmp has been validated.
Write access to /homepages/35/d215549132/htdocs/GLPI/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /homepages/35/d215549132/htdocs/GLPI/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /homepages/35/d215549132/htdocs/GLPI
GLPI_CONFIG_DIR: /homepages/35/d215549132/htdocs/GLPI/config
GLPI_VAR_DIR: /homepages/35/d215549132/htdocs/GLPI/files
GLPI_MARKETPLACE_DIR: /homepages/35/d215549132/htdocs/GLPI/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /homepages/35/d215549132/htdocs/GLPI/files
GLPI_CACHE_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_cache
GLPI_CRON_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_cron
GLPI_DUMP_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_dumps
GLPI_GRAPH_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_graphs
GLPI_LOCAL_I18N_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_locales
GLPI_LOCK_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_lock
GLPI_LOG_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_log
GLPI_PICTURE_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_pictures
GLPI_PLUGIN_DOC_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_plugins
GLPI_RSS_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_rss
GLPI_SESSION_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_sessions
GLPI_TMP_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_tmp
GLPI_UPLOAD_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_uploads
GLPI_INVENTORY_DIR: /homepages/35/d215549132/htdocs/GLPI/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /homepages/35/d215549132/htdocs/GLPI/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/homepages/35/d215549132/htdocs/GLPI/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/homepages/35/d215549132/htdocs/GLPI/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/homepages/35/d215549132/htdocs/GLPI/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/homepages/35/d215549132/htdocs/GLPI/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/homepages/35/d215549132/htdocs/GLPI/vendor/michelf/php-markdown/Michelf)
true/punycode in (/homepages/35/d215549132/htdocs/GLPI/vendor/true/punycode/src)
iamcal/lib_autolink in (/homepages/35/d215549132/htdocs/GLPI/vendor/iamcal/lib_autolink)
sabre/dav in (/homepages/35/d215549132/htdocs/GLPI/vendor/sabre/dav/lib/DAV)
sabre/http in (/homepages/35/d215549132/htdocs/GLPI/vendor/sabre/http/lib)
sabre/uri in (/homepages/35/d215549132/htdocs/GLPI/vendor/sabre/uri/lib)
sabre/vobject in (/homepages/35/d215549132/htdocs/GLPI/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/homepages/35/d215549132/htdocs/GLPI/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/homepages/35/d215549132/htdocs/GLPI/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/homepages/35/d215549132/htdocs/GLPI/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/homepages/35/d215549132/htdocs/GLPI/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/homepages/35/d215549132/htdocs/GLPI/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/homepages/35/d215549132/htdocs/GLPI/vendor/elvanto/litemoji/src)
symfony/console in (/homepages/35/d215549132/htdocs/GLPI/vendor/symfony/console)
scssphp/scssphp in (/homepages/35/d215549132/htdocs/GLPI/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/homepages/35/d215549132/htdocs/GLPI/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/homepages/35/d215549132/htdocs/GLPI/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/homepages/35/d215549132/htdocs/GLPI/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/homepages/35/d215549132/htdocs/GLPI/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/homepages/35/d215549132/htdocs/GLPI/vendor/ramsey/uuid/src)
psr/log in (/homepages/35/d215549132/htdocs/GLPI/vendor/psr/log/Psr/Log)
psr/simple-cache in (/homepages/35/d215549132/htdocs/GLPI/vendor/psr/simple-cache/src)
psr/cache in (/homepages/35/d215549132/htdocs/GLPI/vendor/psr/cache/src)
league/csv in (/homepages/35/d215549132/htdocs/GLPI/vendor/league/csv/src)
mexitek/phpcolors in (/homepages/35/d215549132/htdocs/GLPI/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/homepages/35/d215549132/htdocs/GLPI/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/homepages/35/d215549132/htdocs/GLPI/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/homepages/35/d215549132/htdocs/GLPI/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/homepages/35/d215549132/htdocs/GLPI/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/homepages/35/d215549132/htdocs/GLPI/vendor/paragonie/sodium_compat/src)
symfony/cache in (/homepages/35/d215549132/htdocs/GLPI/vendor/symfony/cache)
html2text/html2text in (/homepages/35/d215549132/htdocs/GLPI/vendor/html2text/html2text/src)
symfony/css-selector in (/homepages/35/d215549132/htdocs/GLPI/vendor/symfony/css-selector)
symfony/dom-crawler in (/homepages/35/d215549132/htdocs/GLPI/vendor/symfony/dom-crawler)
twig/twig in (/homepages/35/d215549132/htdocs/GLPI/vendor/twig/twig/src)
twig/string-extra in (/homepages/35/d215549132/htdocs/GLPI/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/homepages/35/d215549132/htdocs/GLPI/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/homepages/35/d215549132/htdocs/GLPI/vendor/symfony/polyfill-php81)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	gantt                Name: gantt                          Version: 1.0.1      State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cconard96** [comment]
This issue should have already been resolved. Please test with the latest bug fix version of GLPI 10.0 (10.0.3).

**Comment by Lanoixdecoco** [comment]
I upgraded to 10.0.3 today, i reproduced the steps, the issue is still here.

**Comment by cconard96** [comment]
This should be fixed by #12693

**Comment by miqonee** [comment]
No this bug still exists kanban is not displayed, and can only be displayed if debug mode is enabled
![image](https://user-images.githubusercontent.com/108046712/227164182-53d48e15-8a68-4187-aa07-7d287a7c65c8.png)

and here with debug mode
![image](https://user-images.githubusercontent.com/108046712/227164460-7dd28039-5bc7-4b19-bf43-b8800d74e4e1.png)

**Comment by cedric-anne** [comment]
@miqonee 

Your issue does not seems related, as your are using a superadmin profile. Issue was related to read-only users.

**Comment by cconard96** [comment]
There are three other fixes that will be included with 10.0.7 which may resolve your issue though.
Please see: #14294, #13918 and #14333
