### ISSUE TITLE
GLPI 10.0.3 -  Error on import new users from LDAP Directory

### ISSUE THREAD

**Issue by SilvaFernando** [glpi-project/glpi#13396]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3

### Bug description

 Error on import new users from LDAP Directory
![image](https://user-images.githubusercontent.com/53239752/203622136-9e5dc42a-352a-4536-9809-e7ca226b2415.png)

### Relevant log output

```shell
I tried aplly this issue https://github.com/glpi-project/glpi/pull/12794/commits/412b15fa0c9f8e982263149291226e65797fa282

In log i have:
PHP Warning (2): ldap_search(): Search: Operations error in /usr/share/glpi/src/AuthLDAP.php at line 1875
```

### Page URL

https://myglpi/front/ldap.import.php

### Your GLPI setup information

Operating system: Linux c7b77c6e3095 5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022 x86_64
PHP 8.0.23 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, selinux, session, snmp, soap, sockets, sodium, sqlite3, standard, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.37 (AlmaLinux) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Server Software: Percona Server (GPL), Release 42, Revision b0a7dc2da2e
	Server Version: 5.7.39-42
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@cantu-db-glpi-10/glpi
	Host info: cantu-db-glpi-10 via TCP/IP
	
PHP version (8.0.23) is supported.PHP version (8.0.23) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.39) is supported.Database engine version (5.7.39) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/lib/glpi/files/_cache has been validated. Write access to /etc/glpi has been validated. Write access to /var/lib/glpi/files/_cron has been validated. Write access to /var/lib/glpi/files/data-documents has been validated. Write access to /var/lib/glpi/files/_dumps has been validated. Write access to /var/lib/glpi/files/_graphs has been validated. Write access to /var/lib/glpi/files/_lock has been validated. Write access to /var/lib/glpi/files/_pictures has been validated. Write access to /var/lib/glpi/files/_plugins has been validated. Write access to /var/lib/glpi/files/_rss has been validated. Write access to /var/lib/glpi/files/_sessions has been validated. Write access to /var/lib/glpi/files/_tmp has been validated. Write access to /var/lib/glpi/files/_uploads has been validated.Write access to /var/lib/glpi/files/_cache has been validated.
Write access to /etc/glpi has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files/data-documents has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.Write access to /usr/share/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**Comment by trasher** [comment]
10.0.3 is outdated, please first update to latest release and confir the issue still happens.

**Comment by benjimaub** [comment]
I have the same problem with version 10.0.5

**Comment by benjimaub** [comment]
I tried to make a small test with my weak knowledge in php.

I tried to check the validity of the variable $_REQUEST['ldap_filter'] 

![image](https://user-images.githubusercontent.com/29761824/205601714-5557e14a-a294-4423-bee5-5a23375a79c3.png)

my result

![image](https://user-images.githubusercontent.com/29761824/205601842-bcd1527f-f1b1-45af-aa8d-3c4cf18725ea.png)

**Comment by benjimaub** [comment]
I tried to make a small test with my weak knowledge in php.

I tried to check the validity of the variable $_REQUEST['ldap_filter'] 

![image](https://user-images.githubusercontent.com/29761824/205602578-6d399ecf-4e78-4ec7-be87-c6fba9a8f114.png)


my result

![image](https://user-images.githubusercontent.com/29761824/205601842-bcd1527f-f1b1-45af-aa8d-3c4cf18725ea.png)

**Comment by SilvaFernando** [comment]
Hello.
I updated my glpi from 10.0.3 to 10.0.5, same error. :(
 
BR.
Fernando Dias da Silva

**Comment by Rafaeldgs** [comment]
Same error here too!

**Comment by SilvaFernando** [comment]
For solve this, i need uninstall everything in my server.

**Comment by cedric-anne** [comment]
Hi,

> For solve this, i need uninstall everything in my server.

Does this mean that your issue is solved?

**Comment by ftoledo** [comment]
i just update to 10.0.6 and still have issues on ldap search:

*** PHP Warning (2): ldap_parse_result() expects parameter 2 to be resource, bool given in /var/www/html/src/AuthLDAP.php at line 1868

ldap test connection work fine but search failed.

**Comment by cedric-anne** [comment]
#13929 may help to have clearer log messages. Could you apply the patch and check what appears in GLPI logs when you do a LDAP search ?

**Comment by trasher** [comment]
No feedback, I close

**Comment by wesleymolina** [comment]
Mesmo problema aqui, versão 10.0.9
