### ISSUE TITLE
10.0.5 - Images in task are not displaying

### ISSUE THREAD

**Issue by Mika64** [glpi-project/glpi#13424]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Images in task are not displaying, I got a 404 error.
![2022-11-28_11-20](https://user-images.githubusercontent.com/2747286/204253929-367df4bf-b049-4b70-a1ba-0bac769c3985.png)

Images in file attachment are OK.

### Relevant log output

```shell
[28/Nov/2022:07:43:40 +0100] "GET /front/src HTTP/1.1" 404 455 "https://glpi.example.com/front/ticket.form.php?id=20649" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
```

### Steps To reproduce

1. add task
2. copy an image file
3. paste into task
4. save

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.5 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux 505aa07490aa 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 08:57:35 EDT 2022 x86_64
PHP 8.1.11 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_sqlite, posix, session, soap, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at 10.130.3.10 Port 80
)
	Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
Server Software: mariadb.org binary distribution
	Server Version: 10.9.3-MariaDB-1:10.9.3+maria~ubu2204
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@db/glpi
	Host info: db via TCP/IP
	
PHP version (8.1.11) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.9.3) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /glpi/files/_cache has been validated.
Write access to /glpi/config has been validated.
Write access to /glpi/files/_cron has been validated.
Write access to /glpi/files has been validated.
Write access to /glpi/files/_dumps has been validated.
Write access to /glpi/files/_graphs has been validated.
Write access to /glpi/files/_lock has been validated.
Write access to /glpi/files/_pictures has been validated.
Write access to /glpi/files/_plugins has been validated.
Write access to /glpi/files/_rss has been validated.
Write access to /glpi/files/_sessions has been validated.
Write access to /glpi/files/_tmp has been validated.
Write access to /glpi/files/_uploads has been validated.
GLPI data directories are located in a secured path.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_CONFIG_DIR: "/glpi/config"
GLPI_VAR_DIR: "/glpi/files"
GLPI_MARKETPLACE_DIR: "/glpi/marketplace"
GLPI_LOG_DIR: "/glpi/logs"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/glpi/files"
GLPI_CACHE_DIR: "/glpi/files/_cache"
GLPI_CRON_DIR: "/glpi/files/_cron"
GLPI_DUMP_DIR: "/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/glpi/files/_locales"
GLPI_LOCK_DIR: "/glpi/files/_lock"
GLPI_PICTURE_DIR: "/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/glpi/files/_plugins"
GLPI_RSS_DIR: "/glpi/files/_rss"
GLPI_SESSION_DIR: "/glpi/files/_sessions"
GLPI_TMP_DIR: "/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (mail@example@smtp.office365.com)

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Champs supplémentaires         Version: 1.18.2     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.2     State: Installed / not activated               
		Install Method: Marketplace
	tag                  Name: Gestion des tags               Version: 2.10.0     State: Installed / not activated               
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Installed / not activated               
		Install Method: Marketplace

</pre></details>

### Anything else?

that's worked in 10.0.3 (before upgrade)

**Comment by WxxxD** [comment]
Hello,

I have same problem on ticket when you drag and drop image into message body. No problem with file attachment.
Let me know if some info can be usefull.

**Comment by cedric-anne** [comment]
Hi,

It has been fixed by #13446

**Comment by hebval** [comment]
> 

Will try it out today,  thanks for the feedback!

**Comment by hebval** [comment]
It fixed the first issue from Mika64. We're still having troubles with mail collectors containing images tho... Still not having any images displayed when they come from mails.

**Comment by cedric-anne** [comment]
> It fixed the first issue from Mika64. We're still having troubles with mail collectors containing images tho... Still not having any images displayed when they come from mails.

This is another problem, you should a new issue for this.

**Comment by mathbueno26** [comment]
In my case, I went to "Configure => General" and put the application URL, it worked
