### ISSUE TITLE
[error] [http client] answer without content

### ISSUE THREAD

**Issue by jeremydubuc** [glpi-project/glpi#13662]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

![image](https://user-images.githubusercontent.com/116254071/208941638-41358f37-5932-4a1a-b6bf-c6e07a05c9bb.png)

Hi,
my glpi server is on ubuntu, since december 20 my linux pc no longer go up with the glpi agent. The agent goes back but not the information. Does someone have an idea ?

**Comment by jeremydubuc** [comment]
I have this error in php-errors.log
[2022-12-21 17:02:13] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to CommonDBTM::delete() must be of the type array, int given, called in /var/www/html/glpi/src/Inventory/Asset/OperatingSystem.php on line 158 in /var/www/html/glpi/src/CommonDBTM.php at line 1972

**Comment by jeremydubuc** [comment]
I made a capture of the lines described in the error message
![image](https://user-images.githubusercontent.com/116254071/208951402-e8d64ad5-1a6a-4279-a342-e383010a5096.png)
![image](https://user-images.githubusercontent.com/116254071/208951431-cd05235a-ea0a-4867-bf23-f9183ddff5a4.png)

**Comment by jeremydubuc** [comment]
I made a capture of the lines described in the error message
![image](https://user-images.githubusercontent.com/116254071/208951692-9c796926-f7e9-4a1f-93c4-7b4073fb58c7.png)
![image](https://user-images.githubusercontent.com/116254071/208951731-86a78c2b-ec71-4034-8f49-0104df43b6e7.png)

**Comment by trasher** [comment]
Try with latest nightly build, this has been fixed already.

**Comment by jeremydubuc** [comment]
I upgraded to version 10.0.6 (nightbuild) and the problem is not fixed. Someone can help me ?

**Comment by trasher** [comment]
please provide relevant logs

**Comment by jeremydubuc** [comment]
![image](https://user-images.githubusercontent.com/116254071/209108630-20c17c0e-b628-4aaf-8b8e-373835d5ed36.png)

**Comment by jeremydubuc** [comment]
![image](https://user-images.githubusercontent.com/116254071/209109304-21d08f78-e946-41de-b4da-6876da160b6d.png)
![image](https://user-images.githubusercontent.com/116254071/209109319-b8c3a9c0-52ab-4736-ae2d-a97afdc53061.png)
Thank you for your help

**Comment by jeremydubuc** [comment]
I no longer have a problem reassembling my linux computers today, but I have no explanation

**Comment by eriqueSDB** [comment]
I had the same problem, and I managed to solve it in an instance of GLPI 10.0.6 pointing to the native inventory or GLPI Inventory plugin, the problem I had noticed was in the "glpi_agenttypes" table, the only entry, which is ID 1, was with the name "GLPI Inventory Plugin", I took another instance of GLPI 10.0.6 and had the name in "Core", when I changed this and tried to redo the inventory, the inventory was without any problem.

The environment I tested already had FusionInventory and OCS Inventory in 9.x, and GLPI Inventory in 10, I believe that one of the 3 main inventory plugins have changed this, causing GLPI to respond with this "answer without content" message, hope this helps someone.

Acredito também que é o mesmo caso do [issue ](https://github.com/glpi-project/glpi/issues/10959)

![Sem título](https://user-images.githubusercontent.com/102301295/221384070-15cef8b4-edf1-4b57-88a1-9f09c5176861.png)
![asd](https://user-images.githubusercontent.com/102301295/221384089-4cd3e078-6883-41aa-af90-19c8e7fe4ab1.png)

**Comment by cedric-anne** [comment]
@erique-souza 

It should be fixed by #14046
