### ISSUE TITLE
##timelineitems.author## does not show anonymous user email or name

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#13801]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,

When you receive a notification which contents a reply from an anonymous user in the timeline, you get to see the word "myself" instead of the email adress of the user.

![image](https://user-images.githubusercontent.com/63743077/212549897-6ef2f861-b2b3-4410-b562-b54fc8619067.png)

This may be linked to 
[[13240]](https://github.com/glpi-project/glpi/issues/13240)
where email of the anonymous user is not shown in the tickets when he replies to tickets.

### Steps To reproduce

1° Answer from a non glpi user email adress to a ticket
2° Go into the ticket and send a follow up to the anonymous user
3° The anonymous user receives the notification with its original message in it, but instead of seeing its email as author, the author is replaced by the word "myself"

![image](https://user-images.githubusercontent.com/63743077/212550109-d0bc31b9-425d-472a-a168-d726ff07c71e.png)

**Comment by cedric-anne** [comment]
Hi,

#13802 should fix the fact that `Myself` value is shown here. It only appears on PHP 7.4, where `0 == "Myself"` is evaluated to `true`.

I keep this issue open are there is still a lack of information for anonymous users that should be fixed.

**Comment by cedric-anne** [comment]
Hi,

It should be fixed by #13858.

**Comment by joomlafun** [comment]
@cedric-anne tested on 10.0.5 and the name/email of anonymous author still don't show :s with ##timelineitems.author##
![image](https://user-images.githubusercontent.com/63743077/214400095-c5e30c29-008b-4b48-adfd-21cf9d967ad7.png)

**Comment by cedric-anne** [comment]
@joomlafun 

We do not have this information in database, as explained in #13240, so for timeline items, we cannot do anything else.

**Comment by joomlafun** [comment]
@cedric-anne An easy solution would be to add at the top of each descriptions the email or name collected by the collector if the content provided comes from an unregistred user.
