### ISSUE TITLE
Error inserting a letter into the queue

### ISSUE THREAD

**Issue by ak47d** [glpi-project/glpi#13931]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3 / 10.0.6

### Bug description

When adding a comment to some tickets or notification of changes in tickets, an error appears - "Error inserting a letter into the queue.". 

The log shows the following errors:

**If invalid symbols/value:**

[2023-01-10 18:03:42] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_queuednotifications` (`itemtype`, `items_id`, `notificationtemplates_id`, `entities_id`, `headers`, `sender`, `sendername`, `name`, `body_text`, `body_html`, `recipient`, `recipientname`, `messageid`, `mode`, `create_time`, `send_time`, `sent_try`, `documents`) VALUES ('Ticket', '9457', '4', '1', .......................

......................................................................................................

 **Error: Incorrect string value: '\xD0' for column 'name' at row 1**

**If the maximum field size is exceeded:**

[2022-09-28 18:36:08] glpiphplog.WARNING:   *** PHP User Warning (512): [GLPI #0006146] _`%there was a long ticket name here%`_ exceed 255 characters long (265), it will be truncated. in /var/www/glpi/src/CommonDBT>  Backtrace :
  src/CommonDBTM.php:4183                            trigger_error()
  src/CommonDBTM.php:1273                            CommonDBTM->filterValues()
  src/NotificationMailing.php:169                    CommonDBTM->add()
  src/Notification.php:610                           NotificationMailing->sendNotification()
  src/NotificationEventAbstract.php:150              Notification::send()
  src/NotificationEvent.php:187                      NotificationEventAbstract::raise()
  src/Ticket.php:1678                                NotificationEvent::raiseEvent()
  src/CommonDBTM.php:1698                            Ticket->post_updateItem()
  src/ITILSolution.php:330                           CommonDBTM->update()
  src/CommonDBTM.php:1305                            ITILSolution->post_addItem()
  front/itilsolution.form.php:60                     CommonDBTM->add()

The problem appeared repeatedly on different tickets. It was experimentally determined that the problem occurs with tickets that have too many characters in the subject, or supposedly there are some non-standard characters.

How can this problem be fixed? How to limit or truncate automatically the number of characters in a subject? And how to get around the problem with non-standard characters?

### Page URL

/front/ticket.form.php?id=1

### Steps To reproduce

Leave a comment on a problem ticket and get an error

**Comment by trasher** [comment]
Try with latest release

**Comment by ak47d** [comment]
Are you sure this is fixed in the latest release?

**Comment by cedric-anne** [comment]
> Are you sure this is fixed in the latest release? Have there been issues with a similar problem before? Are they closed?

Hi,

Many fixes were done between GLPI 10.0.3 and 10.0.6. Maybe your problem was not fixed, but none of us is able to be sure that there was no fix related to this, because none of us are able to remember of all fixes made in last 4 months.

Anyway, could you give the exact query that fails ?

**Comment by ak47d** [comment]
The value of the 'name' field in the request - 

'[GLPI #0009457] РќРѕРІС‹Р№ РїРѕР»СЊР·РѕРІР°С‚РµР»СЊ РІ РЅР°Р±Р»СЋРґР°С‚РµР»СЏС… FW: 656051. РЎРЎ , РћРћРћ. РџСЂРёРѕР±СЂРµС‚РµРЅРёРµ. Р›РР Рђ 10.12 STD + Р“СЂСѓРЅС‚ РёР»Рё PRO + Р“СЂСѓРЅС‚ + Р”РёРЅР°РјРёРєР° + РњРѕРЅС‚Р°Р¶. 1 Р»РёС†РµРЅР·РёСЏ. РЎРµС‚РµР'

The request itself (its beginning) -   

SQL: INSERT INTO `glpi_queuednotifications` (`itemtype`, `items_id`, `notificationtemplates_id`, `entities_id`, `headers`, `sender`, `sendername`, `name`, `body_text`, `body_html`, `recipient`, `recipientname`, `messageid`, `mode`, `create_time`, `send_time`, `sent_try`, `documents`) VALUES ('Ticket', '9457', '4', '1', '{"Auto-Submitted":"auto-generated","X-Auto-Response-Suppress":"OOF, DR, NDR, RN, NRN"}', 'it@company.com', 'Р•РґРёРЅР°СЏ СЃР»СѓР¶Р±Р° С‚РµС…РЅРёС‡РµСЃРєРѕР№ РїРѕРґРґРµСЂР¶РєРё', '[GLPI #0009457] РќРѕРІС‹Р№ РїРѕР»СЊР·РѕРІР°С‚РµР»СЊ РІ РЅР°Р±Р»СЋРґР°С‚РµР»СЏС… FW: 656051. РЎРЎ , РћРћРћ. РџСЂРёРѕР±СЂРµС‚РµРЅРёРµ. Р›РР Рђ 10.12 STD + Р“СЂСѓРЅС‚ РёР»Рё PRO + Р“СЂСѓРЅС‚ + Р”РёРЅР°РјРёРєР° + РњРѕРЅС‚Р°Р¶. 1 Р»РёС†РµРЅР·РёСЏ. РЎРµС‚РµР',

The problem was temporarily solved by manually changing the field - the name of the application, removing some of the characters of the name

Perhaps there is a problem with database encodings?
https://ru.stackoverflow.com/questions/1021637/mysql-incorrect-string-value

**Comment by trasher** [comment]
> Are you sure this is fixed in the latest release? Have there been issues with a similar problem before? Are they closed?

Are you sure this isn't fixed in the latest release?

**Comment by ak47d** [comment]
Checked. On 10.0.6 the problem also manifests itself. Applied changes https://github.com/glpi-project/glpi/pull/13932 to src/CommonDBTM.php after which the problem was fixed. Notifications in a ticket with a long name are now placed in the notification queue.
I also noticed that the name of the application and the subject of the letter are not cut off, as it should be?

**Comment by cedric-anne** [comment]
> I also noticed that the name of the application and the subject of the letter are not cut off, as it should be?

Previous code was not handling correctly multibyte strings and string were truncated after 255th byte, with proposed fix, truncation is made after 255th char.
Length of your application name was probably higher than 255 bytes but lower than 255 chars.

**Comment by ak47d** [comment]
Thanks! Tried to apply similar changes on 10.0.3, but there is a different CommonDBTM from 10.0.6. As I understand it, the solution to the problem on 10.0.3 is only through upgrading to 10.0.6 and only then making changes to CommonDBTM?

**Comment by cedric-anne** [comment]
Sincerely, applying patches on an older version of GLPI is often a risky operation, as it may require a previously applied patch to work as expected. Current patch could probably be applied on any GLPI 10.0.x version, but the best solution will always be to use the latest GLPI version available.
So here is the important question: why not update to GLPI 10.0.6?

**Comment by ak47d** [comment]
Thanks for the detailed answer. There are plans to upgrade to 10.0.6. While testing it on a test copy.
There are also atypical improvements that need to be transferred to the new version, or possibly included in the release. Including translation improvements (or do they need to be reported in a place other than github?)

**Comment by cedric-anne** [comment]
> Including translation improvements (or do they need to be reported in a place other than github?)

If improvements are related to english language, you can propose a pull request, otherwise, you can propose improvements on https://explore.transifex.com/glpi/GLPI/

**Comment by ak47d** [comment]
Thanks

**Comment by cedric-anne** [comment]
Fixed by #13932 .
