### ISSUE TITLE
Users unable to see their own tickets after update to 10.0.7

### ISSUE THREAD

**Issue by pzbdkp** [glpi-project/glpi#15103]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

We're using simplified interface for all our users, where they can follow status of their own tickets. After update to 10.0.7 users only see their tickets that are created after the update (independent of their status). 
They cannot see older tickets (whether these tickets are still open, pending or closed).

When changing the profile's interface to "standard interface", all users can see all their tickets again.

It looks like a bug in the simplied interface, where users are unable to see their tickets.

### Relevant log output

```shell
No relevant items in log files when reproducing the error.
```

### Steps To reproduce

After update to 10.0.7 users are unable to see their own tickets

### Your GLPI setup information

GLPI 10.0.7 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

**Comment by trasher** [comment]
Please try on latests 10.0/bugfixes nightly build, it should already has been fixed for 10.0.8.

**Comment by pzbdkp** [comment]
Created a testing environment with copy of existing MySQL-database.
Upgraded to 10.0.8, but still the same behavior. User in simplified interface can only see tickets created after the update to 10.0.7

GLPI 10.0.8-dev ( => /var/www/glpi-demo)
Installation mode: TARBALL
Current language:en_GB

**Comment by pzbdkp** [comment]
Did check this further.
When disabling plugin FromCreator, all tickets are displayed for the user.

So it is related to the FormCreator plugin.

**Comment by cedric-anne** [comment]
Hi,

Please open an issue on [plugin repository](https://github.com/pluginsGLPI/formcreator).

**Comment by pzbdkp** [comment]
[Issue 3319](https://github.com/pluginsGLPI/formcreator/issues/3319) created on plugin repository.
