### ISSUE TITLE
Ldap sync deletes permissions and profiles

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#15102]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

We use an Ldap sync cron job that syncs all users once a day. Permissions and profiles are removed and only reassigned when people log in. 

We use the following rules to assign identities and profiles to the synchronized users.

 
RULE OPERATOR = and

<img width="809" alt="Screenshot 2023-07-04 093437" src="https://github.com/glpi-project/glpi/assets/115316656/755c1f09-bdde-433f-ac4f-e618f1f51e23">

The first four rules are used for the IT department employees, while the last rule is for all other users who should not log in but still need to be present in GLPI for assignments.

The only rule executed during LDAP sync is the last one, which has "no rights". The other rules are applied only when the user logs in, which means that IT department employees have no rights and no assignments until they log in.

The individual rules are executed correctly. However, when I perform a complete test of the rule set, only the last one with "no rights" is executed. What could be the reason for this?

Just to clarify, I want all rules to work directly during LDAP synchronization and not just when users log in. Similar to the "No Rights" rule. Because if the users have no entity and no permissions, they are also not available for selection, for example, for assets or tickets. Even if the group assignment is missing, the users won't receive notifications until they log in again, and that could be too late in many cases.

And I have one more question or problem. When the LDAP sync is performed, all users are logged out. Is there a way to prevent that from happening?

**Comment by trasher** [comment]
Please try on latest 10.0/bugfixes nightly build.

**Comment by FreeMacs** [comment]
Just for clarification, I want all the rules to work directly during LDAP sync and not only when the users log in. Similar to the "no rights" rule.

And I have one more question or problem. When the LDAP sync is performed, all users are logged out. Is there a way to prevent that from happening?

**Comment by FreeMacs** [comment]
I have updated to the latest version 10.0.8 and I still have the same problems.

I have also found out that all rules with '(LDAP) ...' only work when logging in and not during the sync itself.

![image](https://github.com/glpi-project/glpi/assets/115316656/2f977d0d-6757-4d98-b4df-1c22cf639b85)
![image](https://github.com/glpi-project/glpi/assets/115316656/c9bd1097-eb47-47a5-b672-081ccefd0c28)

They also don't work when I test the rule set.


Please help!

**Comment by cedric-anne** [comment]
Hi @FreeMacs ,

Could you try with 10.0.10 (many bugs related to LDAP have been solved), and maybe also apply the #15635 patch?

**Comment by trasher** [comment]
Ne feedback from a while, closing

**Comment by FreeMacs** [comment]
sorry i only saw this now, this problem still exists as of today

**Comment by FreeMacs** [comment]
This problem still exists
