### ISSUE TITLE
Black font with dark theme!

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#15606]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

In certain situations, when using a dark theme, the text may turn black instead of white, which affects readability. This occurs when you use text input in your browser (Edge for us) and select the suggested words, but it can also happen occasionally when typing normally without suggestions. Here are a few examples.

![5b0bcae4-577d-48c8-8d90-688b1ba77c61](https://github.com/glpi-project/glpi/assets/115316656/7078865b-629f-49bb-aace-52c8eef19ace)
![bae44cc0-e12b-43e1-a9f9-3519e4bdb97c](https://github.com/glpi-project/glpi/assets/115316656/b3f396f5-2d62-45b5-ba67-2af7c4508448)

**Comment by cconard96** [comment]
This is an issue with Tabler not overriding the default "autofill" styles, so the default provided by the browser (black) is used.

**Comment by cconard96** [comment]
Should be fixed in Taber 1.0.0-beta17

**Comment by cconard96** [comment]
Fixed by #15609

**Comment by FreeMacs** [comment]
I installed version 10.0.10 but still have the same thing with the black font.
