### ISSUE TITLE
Blank/White screen after adding a device

### ISSUE THREAD

**Issue by aha999** [glpi-project/glpi#15833]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.9

### Bug description

Creating an issue. I want to add a device in the Devices category, so i add it. When i finish the issue by pressing the Add button, the website goes blank white. Pressing back in the browser doesn't go back, unless it is pressed fast and multiple times.

### Page URL

glpi/front/ticket.form.php

### Steps To reproduce

1. Start creating an Issue and input all the necesarry information
2. Add a device in the Devices menu/list
3. Press "Add" to submit the Issue
4. the self hosted GLPI website goes blank

**Comment by cedric-anne** [comment]
Hi,

I am not able to reproduce.

First, please try to reproduce on GLPI 10.0.10, this issue may have been already fixed.

Second, please check GLPI logs (files/_logs/php-errors.log) to see if something is added to the error log when this issue happens. When a "blank page" appears, it often means that a fatal error occurs, and GLPI should log it.

**Comment by aha999** [comment]
the "files/_logs/php-errors.log" logs this, when it happens:

[2023-10-19 14:14:26] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Glpi\Toolbox\Sanitizer::isNsClassOrCallableIdentifier(): Argument #1 ($value) must be of type string, array given, called in /var/www/glpi/src/DBmysql.php on line 1287 in /var/www/glpi/src/Toolbox/Sanitizer.php at line 228
  Backtrace :
  src/DBmysql.php:1287                               Glpi\Toolbox\Sanitizer::isNsClassOrCallableIdentifier()
  src/DBmysql.php:1433                               DBmysql::quoteValue()
  src/DBmysql.php:1467                               DBmysql->buildUpdate()
  src/CommonDBTM.php:686                             DBmysql->update()
  src/CommonDBTM.php:1675                            CommonDBTM->updateInDB()
  front/ticket.form.php:84                           CommonDBTM->update()
  public/index.php:82                                require()

**Comment by trasher** [comment]
Please provide (as initilly requested) GLPI setup information. Also, please try without any plugin.

**Comment by aha999** [comment]
Disabling all plugins still causes the same error. Where can i access GLPI setup information ?

**Comment by aha999** [comment]
![slika](https://github.com/glpi-project/glpi/assets/50620416/fa219845-05f3-4b05-abcf-03884cce4ccf)

![slika](https://github.com/glpi-project/glpi/assets/50620416/a9fbbdd3-f844-4300-98bd-8035e50e412a)

After the last screenshot:
![slika](https://github.com/glpi-project/glpi/assets/50620416/9b2b33c7-6ee4-4d5f-a3ee-e001921778a8)

**Comment by cconard96** [comment]
"Please copy and paste information you will find in GLPI in Setup > General menu, System tab."
There is a button in that location that will copy the full system information displayed to your clipboard, and format it nicely for use in GitHub comments.

**Comment by aha999** [comment]
Thank you for information. I renamed some elements for privacy. Here is the output:

```
<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.9 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux test-test10 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.14 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at test-test10.name.si Port 000
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Server Software: Ubuntu 22.04
	Server Version: 10.6.12-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpitest
	Host info: Localhost via UNIX socket
	
PHP version (8.1.2-1ubuntu2.14) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_CONFIG_DIR: "/var/www/glpi/config"
GLPI_VAR_DIR: "/var/www/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/glpi/files"
GLPI_CACHE_DIR: "/var/www/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.9"
GLPI_SCHEMA_VERSION: "10.0.9@77fc44668eaae89b61d95fe606d20d93d66110cd"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: '000.000.00.00', Port: '000', BaseDN: 'DC=ad,DC=test,DC=si', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CN=Glpi
		Helpdesk,OU=Servisi,DC=ad,DC=test,DC=si', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonimni@anonimni-test.ad.test.si)

</pre></details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional fields              Version: 1.21.4     State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alerts                         Version: 1.12.1     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.7     State: Installed / not activated               
		Install Method: Marketplace
	metabase             Name: metabase                       Version: 1.2.4      State: Error / to clean                        
		Install Method: Manual
	mreporting           Name: More Reporting                 Version: 1.7.4      State: Error / to clean                        
		Install Method: Manual
	additionalalerts     Name: Others alerts                  Version: 2.4.0      State: Not installed                           
		Install Method: Marketplace
	yagp                 Name: yagp                           Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace

</pre></details>
```

**Comment by stonebuzz** [comment]
Hi @aha999 

can you check from concerning profil ("Assistance" tab) values from "Associable items to a ticket" option 

![image](https://github.com/glpi-project/glpi/assets/7335054/6a7828a1-a697-4cd6-986e-7eeb69d3bdb7)

**Comment by aha999** [comment]
@stonebuzz i have super-admin privileges, but as mentioned above, i can add for example my computer to the Issue with one method, but not the other (main one).

![slika](https://github.com/glpi-project/glpi/assets/50620416/062a1a7f-fe7f-44ed-bb93-87dc4c7a01a9)

**Comment by trasher** [comment]
I'm not able to reproduce on current nightly, as already said, try with 10.0.10 or latests nightly build.

**Comment by trasher** [comment]
(also, I suspect something else wrong in the ticket; provided error from logs is not related to item linked as far as I can see)

**Comment by ftoledo** [comment]
I have same erro issue at log after update from 10.0.6  to 10.0.10, but i can add devices whitout problems =|
So i think taht log message are come from another event

**Comment by aha999** [comment]
I cannot upgrade to 10.0.10 if i'm not 100% sure that it will fix the problem, because i'm upgrading to 10.0.9 and upgrading to 10.0.10 would mean a new project.

**Comment by trasher** [comment]
Since we do not reproduce, I consider the issue is fixed. Fell free to reopen if you reproduce with latest stable release (do not wait for .11 to be released to test .10...).

**Comment by aha999** [comment]
We updated GLPI to **10.0.10** and **the issue is still here**. Blank screen after creating an issue, if a device was added to the issue.

**Comment by stonebuzz** [comment]
Can you retry by droping this columns (from ```glpi_tickets``` table)

- ``` `items_id` ```
- ``` `itemtype` ```

but it seems that the structure of your GLPI database is really (really!)  inconsistent 

- Several tables that should no longer exist,
- columns that have not been migrated correctly

you need to clean / adapt the structure according to the diff provided by the command

**Comment by aha999** [comment]
Is it possible to solve the posted database inconsistencies automatically?

**Comment by cedric-anne** [comment]
> We are having issues fixing this... Is it possible to solve the posted database inconsistencies automatically?

No, be cause it is nearly imoossible to know why inconsistencies are present.

**Comment by aha999** [comment]
I posted this issue to GLPI forums:

- https://forum.glpi-project.org/viewtopic.php?pid=506321#p506321
