### ISSUE TITLE
impossible to add attachment in ticket

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1663]
Please don't close issue when it is not checked and solved.

Thx

**Comment by satyan01** [comment]
after modification

error

![image](https://cloud.githubusercontent.com/assets/15144026/22110046/99408dfe-de5a-11e6-995c-10d63c09498e.png)

**Comment by trasher** [comment]
> Please don't close issue when it is not checked and solved.

The issue you initially pointed out has been solved. So the ticket has been close. Thanks.

Also, please do not post same messages on different posts. Ask for original issue to be reopen or open another one; not both.

**Comment by satyan01** [comment]
Not solved for me, because it is not possible to add an attachment withour error message.

Anyway. Thank you for your fast answer

**Comment by trasher** [comment]
Other ticket has been closed automatically from PR merge.

Closing this one as duplicate of #1662 since discussion continues other there.
