### ISSUE TITLE
Sharepoint/one drive links are removed

### ISSUE THREAD

**Issue by tograss** [glpi-project/glpi#18717]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

When sending a mail to glpi containing a link to a sharepoint / onedrive file the link gets removed and only the title and image remains.
The mail html looks like this: 
```html
<p class=MsoNormal><o:p>&nbsp;</o:p></p><p class=MsoNormal><a href="https://xxx.sharepoint.com/:w:/g/personal/foo/baa"><span class=MsoSmartlink><span style='text-decoration:none'><img border=0 width=16 height=16 style='width:.1666in;height:.1666in' id="Grafik_x0020_1" src="cid:image001.png@01DB65D7.1534D6C0" alt=docx-Symbol></span> Test_one_drive.docx</span></a><o:p></o:p></p>
```
which looks ok.
I found an existing forum question https://forum.glpi-project.org/viewtopic.php?id=289709 but no solution.

**Comment by trasher** [comment]
Please try with latest 10.0/bugfixes nightly build, it may laready have been fixed.

**Comment by tograss** [comment]
Sorry for the late reply. Unfortunately the bug still exists in the latest bugfix build.

**Comment by tograss** [comment]
I finally had the time to debug this some more. The Problem does not only affect sharepoint links but all anchor tags containing an image. It boils down to that you create nested anchor tags which is illegal.

In more detail:
In Ticket::convertContentForTicket called  in line 1260 in MailCollector.php you replace an inline html image with a place holder:
```html
<p class="MsoNormal">Test <a href="https://xxx-my.sharepoint.com/:w:/g/personal/xxxx/foo">
<span class="MsoSmartlink"><span style="text-decoration:none"><img border="0" width="16" height="16" style="width:.1666in;height:.1666in" id="Grafik_x0020_1" src="cid:image001.png@01DB7884.5D3E9400" alt="docx-Symbol"></span>&nbsp;Test_one_drive.docx</span></a></p>
```
becomes
```html
<p class="MsoNormal">Test <a href="https://xxx-my.sharepoint.com/:w:/g/personal/xxxx/foo">
<span class="MsoSmartlink"><span style="text-decoration:none"><p>#326a47fc-125a9f1e-67a4853e520f57.65276840#</p></span>&nbsp;Test_one_drive.docx</span></a></p>
```
#326a47fc-125a9f1e-67a4853e520f57.65276840# is replaced with an anchor tag referencing  the internal file. I guess to allow showing the large image when clicking on an image in the ticket. So the string becomes (after html decoding)  
```html
<p class="MsoNormal">Test <a href="https://xxx-my.sharepoint.com/:w:/g/personal/xxxx/foo"> <span class="MsoSmartlink"><span style="text-decoration:none"><p><a href="/front/document.send.php?docid=24985&itemtype=Ticket&items_id=2502060004" target="_blank" ><img alt="e4af3f5a-8719a875-6785281b1e9387.65145433" width="32" src="/front/document.send.php?docid=24985&itemtype=Ticket&items_id=2502060004" /></a></p></span>&nbsp;Test_one_drive.docx</span></a></p> <p class="MsoNormal"></p>
```
As stated this contains nested html tags, which at least chrome and firefox just ignore the outer anchor tag. Unfortunately I have no good idea how to solve this and keep the behavior that an image opens in this pop out window. Do you have nay suggestions how this should be handled ?

**Comment by cedric-anne** [comment]
There is a fix proposal for this issue, see #18397.
