### ISSUE TITLE
Attaching file with name in Russian

### ISSUE THREAD

**Issue by n0c1ip** [glpi-project/glpi#1917]
Version 9.1.1
When you attach a file to the ticket and file name contains more than one word in Russian, first word is dissapears.
Also found [this ](http://forum.glpi-project.org/viewtopic.php?id=47229)topic on forum.

![files_test](https://cloud.githubusercontent.com/assets/13107402/23710885/06ab8230-0440-11e7-8a66-9ab00c28fac2.jpg)

**Comment by trasher** [comment]
I've just tested with the 9.1/bugfixes branch; and I cannot reproduce the initial issue; I guess this has been fixed.

Feel free to test with that branch; and reopen if problem persits.

**Comment by Dmitriy71RU** [comment]
In 9.1.2 this problem still exists. 
![glpiissue](https://cloud.githubusercontent.com/assets/28724138/26092859/f28d7512-3a1b-11e7-85ff-5e991632dc24.png)

**Comment by trasher** [comment]
Could you checks the logs and see if there is any extra information?

**Comment by Dmitriy71RU** [comment]
You mean this log?
![default](https://cloud.githubusercontent.com/assets/28724138/26095245/9af721e0-3a25-11e7-918d-97146d177854.png)

**Comment by trasher** [comment]
Non, I mean system (depends on your system) and/or glpi logs (in glpi/files/_log)

**Comment by Dmitriy71RU** [comment]
Here is a section of \var\log\apache2\access.log which is supposedly related to this uploaded file (highlited 3 strings)
![1](https://cloud.githubusercontent.com/assets/28724138/26105595/4199d37e-3a4b-11e7-85a0-09fa2666c417.png)
[access.txt](https://github.com/glpi-project/glpi/files/1004319/access.txt)

The only recently-updated logs in glpi/files/_log are cron.log and event.log. The latter one contains only login attempts history. 

Is it sufficient or should I seek elswhere?

**Comment by trasher** [comment]
OK, thank you, there is unfortunately no error... Will have to try to reproduce then :/

**Comment by Dmitriy71RU** [comment]
Try to copy from here exactly the same filename as I used:

Файл с очень длинным названием

**Comment by Dmitriy71RU** [comment]
I've noticed that if filename starts with a latin symbol or a number, it will not be cut, even if the following symbols are cyrillic: 
новый документ.pdf ===> документ.pdf
1новый документ.pdf ===> 1новый документ.pdf

**Comment by trasher** [comment]
I'm still unable to reproduce...

I've tested uploading a document with the last filename copy/pasted either using drag & drop or upload button... :/ I get the full filename each time ; as expected.

Either there is a parameter or an environment difference beetween you and me. But if I cannot reproduce the problem, I cannot get hits fixed.

Note:
OS: linux,
Browser: firefox
GLPI: 9.1.7 (current 9.1/bugfixes)

**Comment by AnaelMobilia** [comment]
Problem not reproduced on Windows 10 / firefox / GLPI 9.2.1

@Dmitriy71RU  Is the problem still reproducible for you ?
Which version of Opera ? Which version of GLPI ? Russian version of windows ?
Could you, please, attach an exemple of failing file ?

Regards,
Anael

**Comment by trasher** [comment]
No feedback, closing. Please check again with 9.2.
