### ISSUE TITLE
Attachments into tickets created by mail receiver

### ISSUE THREAD

**Issue by moriame** [glpi-project/glpi#1933]
Hi,

We just install release 9.1.2
We test mail receiver with some attachments inside.

The created tickets is not what we expected.
In fact, this is the original email sent:
![image](https://cloud.githubusercontent.com/assets/536434/23790204/78fcd3b8-057e-11e7-9f19-3badba1e3cb7.png)

And this is the result into GLPI:
![image](https://cloud.githubusercontent.com/assets/536434/23790217/88786f78-057e-11e7-953f-a008a51ca7e1.png)
![image](https://cloud.githubusercontent.com/assets/536434/23790224/8bda6112-057e-11e7-8b09-dc2a27e1ae0a.png)

We expected that attachments are include inside the ticket to better understand the mail sent by our customers: 
![image](https://cloud.githubusercontent.com/assets/536434/23790408/376a24f4-057f-11e7-9628-162000fdc905.png)

**Comment by trasher** [comment]
Could you try with the 9.1/bugfixes branch? I remember I've already seen something similar that has been fixed; can't remember where and on which branch unfortunately.

**Comment by trasher** [comment]
Also, I guess problem is the same than #1929

**Comment by moriame** [comment]
Try the branche 9.1/bugfixes branch : still the same error.
I don't know if that can help, but we are using Lotus Notes for mail client.

Can't try another email client :/

![image](https://cloud.githubusercontent.com/assets/536434/25039439/d399416c-2103-11e7-86a4-ad017a6a53d6.png)

**Comment by tomolimo** [comment]
Hello,
We have the same issue with Outlook (and Exchange sever).
regards
Tomolimo

**Comment by trasher** [comment]
I don not think this is related to the mail client used; it sounds like a path issue (see #1929)
