### ISSUE TITLE
Drag and drop not working in form editor

### ISSUE THREAD

**Issue by MHAM2025** [glpi-project/glpi#19737]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0-beta3

### Bug description

Hi, 
On the form editor, if I try to move a question nothing happen. The cursor changing to a hand but the question not moving.

### Relevant log output

```shell

```

### Steps To reproduce

1. Go to Assistance > Forms > select a form
2. Try to move a question
3. Nothing move

**Comment by ccailly** [comment]
Hi, thank you for your feedback.
I can't reproduce your problem.
When I try to reproduce your case, I can well move the elements and reorganize them.
I found a small bug that occurs when you have several sections, corrected with #19755.

If you manage to reproduce your problem, can you provide me with a video of the bug in action?

**Comment by MHAM2025** [comment]
Hi, thanks for your reply. 
I found out that is the question comes from an horizontal layout i can move it, but not in the vertical layout.
When i grab the question, there is the hand but then it seems that i didn't keep it.
I hope the video will help you. 

https://github.com/user-attachments/assets/47a97a72-7cf2-4ce0-a405-4836c582f697

**Comment by trasher** [comment]
Maybe could you tets with an up-to-date nightly build, since there were many issues fixed since beta3.

**Comment by MHAM2025** [comment]
Hi, 
I clean glpi cache and open browser's console. 
I have 404 error for GET https://server/glpi/public/css_compiled/css_core_palettes.min.css?v=ac21998409dd73291b3ef48d76facf845055a388

I know that I encountered a similar problem with conditions because of a bad server config. (i use WAMP)

I will test with a nightly build

**Comment by cedric-anne** [comment]
> I have 404 error for GET https://server/glpi/public/css_compiled/css_core_palettes.min.css?v=ac21998409dd73291b3ef48d76facf845055a388

This should be fixed by #19771, but it is probably not the cause of your initial issue.

**Comment by MHAM2025** [comment]
Hi, I update with beta4. I still can't move the questions. 
I don't have errors in the console. 
I have a deprecation : `-ms-high-contrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard. `
But i don't think it's related.

**Comment by cedric-anne** [comment]
What browser are you using ?

**Comment by MHAM2025** [comment]
I'm using Edge

**Comment by cedric-anne** [comment]
What is the version of your Edge browser ?

**Comment by cconard96** [comment]
I tested this before and it seemed to be working in both layouts, but I tested it again and now it isn't working at all. I found that sorting partially works again when removing the `handle` option but the behavior seems inconsistent with where the dragged element gets placed and the drag image includes sibling elements/questions.

Google Chrome Version 138.0.7204.49
I did recently update Chrome from version 136 after my initial testing of the Forms.

It does work properly even with the `handle` in Firefox 140.0.1.

Seems like it could be a Chromium issue but I do not notice any issues with sorting in the Kanban, display preferences, custom assets field editor or even the helpdesk tiles config.

**Comment by jxchinaquanfu** [comment]
I have the same issue, horizontal layout  can move it, but not in the vertical layout.  Both  Chrome version  138.0.7204.158  and 113.0.5672.64. But with FireFox is no problem.

**Comment by AdrienClairembault** [comment]
Thanks for the report, I confirm the issue.

#20552 should fix it.
