### ISSUE TITLE
Slow performance and crashes when managing the form - glpi 11-rc1

### ISSUE THREAD

**Issue by lucaslevi-consultor-glpi** [glpi-project/glpi#20416]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Contribution description

Hey everyone,

I'm opening this issue so we can talk about how slow the form management is in version 11 of the system.

It's already at version 11-rc1, and compared to how the forms plugin works now, this new version is still pretty slow in the form management tab.

As shown in the video below, when accessing the form in the open ticket view, the speed is normal. But when accessing the same form in the administration section, there is this delay and you can also notice some crashes when trying to click on the questions.

My intention here is to report that this part is still not working well, in my opinion. Thinking about environments that depend heavily on the form, imagining that the migration from 10 to 11 would be done the way it is now, it would bring a lot of difficulties in manipulating forms as an administrator.

That's it, best regards!

https://github.com/user-attachments/assets/b886dec8-a78f-41a7-a669-61aebfdf2824

**Comment by cconard96** [comment]
Related to #19893

**Comment by AdrienClairembault** [comment]
I've opened 3 PR that should help with this.

However, this issue is not totally fixed in the following cases:
- When using the bitwarden browser extension, there is a very high CPU usage that slow down the page initial loading (see https://github.com/bitwarden/clients/issues/8699, no fix available as this time) . No idea if others password managers have the same issue.
- When using google chrome or other chrome based browsers, the page is much slower. I'll keep looking for improvements here but it is frustrating because the issue doesn't exist at all on firefox (open to suggestions).

**Comment by cconard96** [comment]
I also noted that the visibility conditions part sends the entire form data to the server every time the condition editor re-renders which is every time you add/delete/change conditions. If possible, it would be better to only send the required data and only render the changed conditions instead of every condition. This may not matter much in real uses but if you have a lot of conditions, like in the E2E tests, it gets quite slow.

**Comment by lucaslevi-consultor-glpi** [comment]
@AdrienClairembault Regarding browser performance, the problem is that most people use Chrome, so it will be complicated if the version is released with these performance issues. If we take the current version 10, it works very smoothly both in terms of form management and ticket handling (unlike version 11).

If you can address this issue, I believe it will have less impact on users who will be using the new version right after its release.

**Comment by AdrienClairembault** [comment]
We have a lot of improvements coming in #21179, it should be much better on chrome now.

**Comment by lucaslevi-consultor-glpi** [comment]
@AdrienClairembault Thanks for the feedback!

I have a list of tests noting problems found in the current rc5 version. I will be repeating the tests, including the performance test.

I look forward to the release.

**Comment by lucaslevi-consultor-glpi** [comment]
@AdrienClairembault Do these improvements also extend to the part of the call within the call, in this case, the loading time?

**Comment by cedric-anne** [comment]
Hi,

Most performances issues have been fixed. If you encounter performances issues on specific cases, please open new issues.

**Comment by lucaslevi-consultor-glpi** [comment]
@cedric-anne All right, the performance within the call is still the same as I showed in the video. It's sad to say, but I'm going to get a new base from 10 and update again to 11 to see if it has any different effect.

But what I reported in the video about the performance within the call, those crashes, etc., apparently remains the same.

**Comment by lucaslevi-consultor-glpi** [comment]
@cedric-anne  Sorry, the delays I am referring to are more related to calls. I am mentioning here the issue #21115   I had opened about this. I understand it is more critical because it will affect the call handling experience.

**Comment by AdrienClairembault** [comment]
Lets keep it in the dedicated issue then, I'll take a look.

**Comment by lucaslevi-consultor-glpi** [comment]
thanks @AdrienClairembault
