### ISSUE TITLE
[9.1.6] mailgate assign randomly user/technician

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#2516]
Hi,

I have upgrade my GLPI from 9.1.2 to 9.1.6.
Since version 9.1.6, the mailgate assign randomly a user and a technician to a new tickets received by mail.

Is-it possible to fix it ?

Thanks

**Comment by barbuslex** [comment]
After 24h of operation, GLPI stop assign automatically a bad user and technician on ticket from mailgate.
But i have a new issue. The attachment has a bad user (Random user too) : 
![image](https://user-images.githubusercontent.com/113057/28673141-12b59410-72e2-11e7-956b-6e3cb40408b8.png)

A similar issue in #641 

Can you fix it please ?

Thanks in advance,

++

**Comment by ProEdgeMaster** [comment]
Hello,

I subscrive the issuue report.

Best Regards Filipe

**Comment by ProEdgeMaster** [comment]
Hello,

 A temporary solution:

    **Go to:** Setup -->"Default Values"--> "Pre-select me as a technician when creating a ticket" :: change to no.

![glpi](https://user-images.githubusercontent.com/1896039/28871335-064b0658-777c-11e7-8ef4-87724ebb7302.PNG)

Best Regards,
    Filipe

**Comment by CSSassess** [comment]
Thank you Filipe,

We too recently upgraded to 9.1.6 and are experiencing the same issue.
Mailgate retrieved 8 messages. We have no automatic assignment rules in place and all mailgate tickets should arrive as "new". Instead all 8 were "processing" with 3 assigned to one technician, 3 to another, and the last 2 to one more tech.

Turning off "pre-select me as technician" may work, but of course now adds extra steps to the majority of our tickets (which do not come in via mailgate).

Regards,
Robert

**Comment by ProEdgeMaster** [comment]
hi,

 change [GLPIROOT]\inc\ticket.class.php at line 1584

change the condition form

// fill auto-assign when no tech defined (only for tech)
      if ($_SESSION['glpiset_default_tech']
          && $_SESSION['glpiactiveprofile']['interface'] == 'central'
          && (!isset($input['_users_id_assign'])
              || $input['_users_id_assign'] == 0)) {
         $input['_users_id_assign'] = Session::getLoginUserID();
      }


to


 // fill auto-assign when no tech defined (only for tech)
      if (!Session::isCron()
          && $_SESSION['glpiset_default_tech']
          && $_SESSION['glpiactiveprofile']['interface'] == 'central'
          && (!isset($input['_users_id_assign'])
              || $input['_users_id_assign'] == 0)) {
         $input['_users_id_assign'] = Session::getLoginUserID();
      }


Now, Turning on "pre-select me as technician"

Best regards,
     Filipe Figueiredo

**Comment by CSSassess** [comment]
Hi,
Updated ticket.class.php at line 1584 as proposed.
This seems to be working correctly now.

Thanks!

**Comment by dabou** [comment]
I think this bug was corrected with the issue #2583 and the commit is merged into 9.1/bugfixes.

**Comment by Armin83** [comment]
@barbuslex barbuslex please close the issue it should be solved with the latest version. You can follow 3192 for special variation of the bug.

**Comment by trasher** [comment]
Fixed in latest releases

**Comment by dilona** [comment]
Hello! We have updated version of GLPI to 9.2.2 but the problem still exists.
Processing ticket:
![image](https://user-images.githubusercontent.com/31918974/37080113-2751ca42-21f6-11e8-8488-4b65062a0c45.png)
Historical:
![image](https://user-images.githubusercontent.com/31918974/37080264-a896f316-21f6-11e8-8b72-d51371b108f4.png)
