### ISSUE TITLE
Problem with session: "Empty username or password"

### ISSUE THREAD

**Issue by dilona** [glpi-project/glpi#2745]
Hi! 
We have a problem with sessions. When log out and log in again appears "Empty username or password" (login and password saved).

Software: GLPI 9.1.1, php7.0, mysql 5.7.19, Ubuntu 16.04
![image](https://user-images.githubusercontent.com/31918974/30417850-c81ac488-9939-11e7-8f66-7473d651078c.png)

1. Log in with the saved username and password (When you first start the browser).
2. Logout -> redirect to /index.php?noAUTO=1
3. Username/password is still saved. Click "Submit"
![image](https://user-images.githubusercontent.com/31918974/30419116-ed1aed5e-993d-11e7-8807-39cedbc0327c.png)
4. Appear "Empty username or password". Then click "Log in again"
![image](https://user-images.githubusercontent.com/31918974/30419549-6be52eb4-993f-11e7-9eb4-7b2b56018aaf.png)
5. Go to /index.php?noAUTO=1 -> Click "Submit" ->  Appear "Empty username or password". It repeats permanently.
If refresh the page (/index.php?noAUTO=1) it works correct.

**Comment by trasher** [comment]
Hello,

Could you please try with 9.1.6? 9.1.1 is quite old, and many bugs have been fixed since; maybe your problem has already been solved..

**Comment by dilona** [comment]
Hello! 
We have updated version of GLPI to 9.1.6 but the problem still exists. 
![image](https://user-images.githubusercontent.com/31918974/30579611-0f36ebee-9d22-11e7-92d5-a9bfedae2b08.png)
Noticed that this error appears only in web browsers with a base of Chromium like Google Chrome (ver. 59, 61), Yandex Browser (ver. 17). In the browser Mozilla Firefox has no this problem.

**Comment by trasher** [comment]
I'm not able to reproduce this issue... But I guess it should be fixes as of GLPI 9.2 since there were several changes on the login. Could you try to reproduce using the 9.2-RC2 that was published yesterday?
Or wait until next week for the 9.2 final to be out.

**Comment by dilona** [comment]
Thanks a lot. After update to 9.2 the problem is solved.
