### ISSUE TITLE
[9.2] image insertion in mail ticket notification

### ISSUE THREAD

**Issue by kelior** [glpi-project/glpi#2869]
Since the 9.2 upgrade, when we receive a mail notification on a ticket update,
the images linked in the ticket do not appear like they used to do : 

Here is the result we get on the mail :
![image](https://user-images.githubusercontent.com/19959600/31006591-953a6bf2-a4fd-11e7-8130-b89c4faf4622.png)
It seems the link to the docid is not complete.

**Comment by alias59** [comment]
Hello,
You have move the folder who containt the image after update ?
Regards

**Comment by kelior** [comment]
no if I access the full url  (http://10.128.6.69/glpi/front/document.send.php?docid=3488) in my browser the image is displayed correctly.

**Comment by alias59** [comment]
Check rules the folder ( Write and Reader ) ?

**Comment by alias59** [comment]
Check general configuration 
address Web : ![image](https://user-images.githubusercontent.com/24585721/31010800-5d238294-a50c-11e7-8fb7-95abd2780471.png)

**Comment by kelior** [comment]
alright the problem is since version 9.2, you can insert images directly into the ticket with tinyMCE.
And it works by puttin an img tag like so 
`<img alt="a74e68b4-d9d62df8-59cca693a30978.38063338" height="106" width="289" src="/glpi/front/document.send.php?docid=3488">`

When the notification is sent, the content of the ticket is copied in the mail with the same src.(missing the root)

**Comment by babaymaster** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/32533688/31212835-569e625e-a9bc-11e7-8acb-1f7f8ca6da16.png)

**Comment by babaymaster** [comment]
as same problem. bad link image in ticket

![image](https://user-images.githubusercontent.com/32533688/31216687-f32869c4-a9cd-11e7-9861-bf0bfe655671.png)

**Comment by rjmontenegro** [comment]
Same on my installation 9.2 (mailgate ticket creation):

![glpi](https://user-images.githubusercontent.com/6449156/31515898-c2807b2e-af8e-11e7-94ff-d73ba0a21a67.png)

**Comment by alias59** [comment]
@kelior, Have you find solution ?

**Comment by babaymaster** [comment]
no, wait new realease,,,,

**Comment by orthagh** [comment]
Hello guys, 
We found a solution this issue.
We embed image as attachments, the correction is #3085 and should be in 9.2.1 release.
So future mail notifications will work.

**Comment by orthagh** [comment]
And in #3092 (will be also released in 9.2.1) mail collect of inline pictures should work

**Comment by dbegit** [comment]
same problem with 9.2.1

**Comment by kelior** [comment]
It is fixed on my end

**Comment by rjmontenegro** [comment]
I'm still experiencing problems after upgrading to 9.2.1.

![01](https://user-images.githubusercontent.com/6449156/33012593-588b90c8-cdd9-11e7-92a7-f1fe48f42de4.png)
Ok, on notification after mailgate (new ticket).

![02](https://user-images.githubusercontent.com/6449156/33012663-840fb670-cdd9-11e7-9f33-ad857ca40e24.png)
Wrong, on ticket...

**Comment by cvscg** [comment]
The problem probably comes from here : 

- inc/html.class.php:5466
`$fullpath = GLPI_DOC_DIR."/".$image['filepath'];`
to
`$fullpath = "/".$image['filepath'];`

**Comment by lekzz** [comment]
The inc/html.class.php:5466 fixes some of the issue but not all, inline mailed messages still have the wrong url, fix:

inc/html.class.php:5474

`                  if ($addLink) {
                     $out .= '<a href="'.$CFG_GLPI['root_doc'].
                             '/front/document.send.php?docid='.$id.
                             '" target="_blank"><img alt="'.$image['tag'].
                             '" height="'.$height.'" width="'.$width.
                             '" src="'.$CFG_GLPI['root_doc'].
                        '/front/document.send.php?docid='.$id.'" /></a>';
                  } else {
                     $out .= '<img alt="'.$image['tag'].
                             '" height="'.$height.'" width="'.$width.
                             '" src="'.$CFG_GLPI['root_doc'].
                             '/front/document.send.php?docid='.$id.'" />';`

to

`                  if ($addLink) {
                     $out .= '<a href="/front/document.send.php?docid='.$id.
                             '" target="_blank"><img alt="'.$image['tag'].
                             '" height="'.$height.'" width="'.$width.
                             '" src="/front/document.send.php?docid='.$id.'" /></a>';
                  } else {
                     $out .= '<img alt="'.$image['tag'].
                             '" height="'.$height.'" width="'.$width.
                             '" src="/front/document.send.php?docid='.$id.'" />';`

**Comment by lekzz** [comment]
Also it seems to mess up the email notifications with more then just one image.

When creating a new ticket or doing a follow up using the website with mutliple images only the first gets used in the notification.
But even funnier when doing the same using email, a preview of the 2nd image is shown in the mail. But when clicking on it you will be taken to the first image.

Also it seems to want to resize/crop/whatever the first image using the website, but not the other images.

**Comment by cvscg** [comment]
It does not work even by changing / removing variables, someone to an idea? Because it's still a critical function ... 👎

**Comment by lekzz** [comment]
The changes work for me but only on new uploaded images, not existing. Guess the generated tags are saved in the database.

**Comment by Claudissimo** [comment]
I have amended the inc/html.class.php file but it is still not working.
We need a fix uiclky guys please.

Thank you for your support

![screeshot](https://user-images.githubusercontent.com/34235302/33547631-f7f0929c-d8e4-11e7-9428-c49590fdf05a.png)

**Comment by okvok** [comment]
Hi. Confirm. The changes work. Thank you!

**Comment by SoluNeXT** [comment]
Hi everybody
Corrected the code for images previews problem in tickets. The RegEx replacement is not working correctly. As I'm not a regex pro, i've made str_replace corrections. Here are the lines modified : 

File : inc/notificationeventmailing.class.php
Line : ~157

```
               foreach ($document_items as $doc_i_data) {
/* ADD LINE DenisC BEGIN */
				  $doc = new Document();  
/* ADD LINE DenisC END */
                  $doc->getFromDB($doc_i_data['documents_id']);

```

Line : ~236

```
            // replace img[src] and a[href] by cid:tag in html content

            foreach ($inline_docs as $docID => $tag) {
/* REMOVED LINES DenisC BEGIN */
/*               $current->fields['body_html'] = preg_replace([
                     '/src=["\'].*document\.send\.php\?docid='.$docID.'["\']/',
                     '/href=["\'].*document\.send\.php\?docid='.$docID.'["\']/',
                  ], [
                     "src=\"cid:$tag\"",
                     "href='".$CFG_GLPI['url_base']."/front/document.send.php?docid=$docID'",
                  ],
                  $current->fields['body_html']);

*/
/* REMOVED LINES DenisC END */
/* ADD LINE DenisC BEGIN */
				$current->fields['body_html'] = str_replace('src="/front/document.send.php?docid='.$docID.'"','src="cid:'.$tag.'"',$current->fields['body_html']);
				$current->fields['body_html'] = str_replace('href="/front/document.send.php?docid='.$docID.'"','href="'.$CFG_GLPI['url_base'].'/front/document.send.php?docid='.$docID.'"',$current->fields['body_html']);
/* ADD LINE DenisC END */
            }

            $mmail->Body   .= $current->fields['body_html'];
            $mmail->AltBody = $current->fields['body_text'];
         }
```

Hope it will help some of you.
Cheers
Denis/SoluNeXT
