### ISSUE TITLE
Problems upgrading from 9.1.2 to 9.2.1

### ISSUE THREAD

**Issue by sebelk** [glpi-project/glpi#3427]
* Steps to reproduce (which actions have you made) :

1) extract the tarball of glpi-9.2.1.tar.gz and launch the upgrade process

* Expected result :

2) GLPI 9.2.1 running

* Actual result :

```
2018-01-12 13:25:50 [@soporte.silicon-aid.com]
  *** MySQL query error:
  SQL: INSERT INTO `glpi_notifications_notificationtemplates`
                       (`notifications_id`, `mode`, `notificationtemplates_id`)
                       SELECT `id`, `mode`, `notificationtemplates_id`
                       FROM `glpi_notifications`
  Error: Duplicate entry '93-42-0' for key 'unicity'
  Backtrace :
  inc/dbmysql.class.php:215                          
  install/update_92_921.php:313                      DBmysql->queryOrDie()
  inc/update.class.php:398                           update92to921()
  install/update.php:457                             Update->doUpdates()
  install/update.php:564                             doUpdateDb()

```

* URL of the page :

https://my.example.com/install/update.php
* Screenshot of the problem (if pertinent) :

![spectacle ve4647](https://user-images.githubusercontent.com/4109256/34885489-e7146c90-f79e-11e7-82b0-d38d30780744.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

This is my current glpi, from it I copied files in order to upgrade (I've disabled all plugins):

```
Operating system: Linux soporte.example.com 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64
PHP 5.4.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bz2, calendar, ctype, curl, date, dom,
	ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, libxml, mbstring, mhash, mysql, mysqli, openssl,
	pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer,
	wddx, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="200M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_qos/11.5 mod_perl/2.0.10 Perl/v5.16.3 ()
	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Server Software: MariaDB Server
	Server Version: 5.5.56-MariaDB
	Server SQL Mode: 
	Parameters: glpi@localhost/glpidb
	Host info: Localhost via UNIX socket
	
OK/var/www/html/config : OK
OK/var/www/html/files : OK
OK/var/www/html/files/_dumps : OK
OK/var/www/html/files/_sessions : OK
OK/var/www/html/files/_cron : OK
OK/var/www/html/files/_graphs : OK
OK/var/www/html/files/_lock : OK
OK/var/www/html/files/_plugins : OK
OK/var/www/html/files/_tmp : OK
OK/var/www/html/files/_rss : OK
OK/var/www/html/files/_uploads : OK
OK/var/www/html/files/_pictures : OK
OK/var/www/html/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Enforcing
OKSELinux boolean configuration for httpd_can_network_connect --> on
Some features may require this to be onSELinux boolean configuration for httpd_can_network_connect_db --> off (Some features may require this to be on)
OKSELinux boolean configuration for httpd_can_sendmail --> on
```

Please could you help me?

**Comment by sebelk** [comment]
Hi,

I've retried droping and importing again the DB dump, but now I have this error:

```
  *** MySQL query error:
  SQL: ALTER TABLE `glpi_tickets` DROP INDEX `slas_id` ,
ADD INDEX `slts_ttr_id` (`slts_ttr_id`) ,
ADD `time_to_own` DATETIME DEFAULT NULL   AFTER `due_date` ,
ADD INDEX `time_to_own` (`time_to_own`) ,
CHANGE `slalevels_id` `ttr_slalevels_id` INT(11) NOT NULL DEFAULT '0'  
  Error: Unknown column 'due_date' in 'glpi_tickets'
  Backtrace :
  inc/dbmysql.class.php:215                          
  inc/migration.class.php:637                        DBmysql->queryOrDie()
  install/update_92_921.php:72                       Migration->migrationOneTable()
  inc/update.class.php:398                           update92to921()
  install/update.php:457                             Update->doUpdates()
  install/update.php:564                             doUpdateDb()

```

Please, any ideas?

Thanks in advance

**Comment by trasher** [comment]
Several issues has been fixed as of 9.2.2. But anyways, you have to entirely drop the database, restore your backup and the do the update.
Your issues are mainly becsue you've tried an update that fails, and you try to run it once again.

**Comment by apeyrou** [comment]
Hello,

please re-open the ticket... 
the problem is still existiing...

![glpi-nok 9 2 1 et 9 2 2](https://user-images.githubusercontent.com/33878364/37201296-89077cfe-2387-11e8-929c-e518cee04adc.PNG)

**Comment by trasher** [comment]
"you have to entirely drop the database, restore your backup and the do the update.", but it sems you did not.

**Comment by apeyrou** [comment]
Yes i did

Le ven. 9 mars 2018 10:53, Johan Cwiklinski <notifications@github.com> a
écrit :

**Comment by Langlais115** [comment]
Same Error here.
I'm in version 9.2 and try to upgrade to 9.2.2. All plugins are disabled.
When I try to upgrade I receive the following:

> Mise à jour
Connexion à la base de données réussie
Mise à jour en 9.2.1

Changement de la structure de la base de données - glpi_slas (1 seconde)
9.2.1 multiple alter in glpi_slas - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_slas` ADD INDEX `slms_id` (`slms_id`) - L'erreur est Key column 'slms_id' doesn't exist in table


Below is the structure and content of that table:
_CREATE TABLE `glpi_slas` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `entities_id` int(11) NOT NULL DEFAULT '0',
  `is_recursive` tinyint(1) NOT NULL DEFAULT '0',
  `comment` text COLLATE utf8_unicode_ci,
  `resolution_time` int(11) NOT NULL,
  `calendars_id` int(11) NOT NULL DEFAULT '0',
  `date_mod` datetime DEFAULT NULL,
  `date_creation` datetime DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;_

--
-- Content of the table `glpi_slas`
--

_INSERT INTO `glpi_slas` (`id`, `name`, `entities_id`, `is_recursive`, `comment`, `resolution_time`, `calendars_id`, `date_mod`, `date_creation`) VALUES
(1, 'Une semaine', 0, 0, '', 7, 2, '2011-11-22 09:41:56', NULL);_

And as the error message is saying the column **slms_id** doesn't exist

**Comment by Langlais115** [comment]
After modifying the script [update_92_921.php](https://github.com/glpi-project/glpi/blob/9.2/bugfixes/install/update_92_921.php) (starting line 167) as follow it's working fine:
From:
##########################
```
   // Changing the structure of the table 'glpi_slts'
   if ($DB->tableExists('glpi_slts')) {
      $migration->renameTable('glpi_slts', 'glpi_slas');
      $migration->migrationOneTable('glpi_slts');
      $migration->changeField('glpi_slas', 'slas_id', 'slms_id', 'integer');
      $migration->dropKey('glpi_slas', 'slas_id');
      $migration->addKey('glpi_slas', 'slms_id');
   }
```
##########################
To:
##########################
```
   // Changing the structure of the table 'glpi_slts'
   if ($DB->tableExists('glpi_slts')) {
      $migration->renameTable('glpi_slts', 'glpi_slas');
      $migration->migrationOneTable('glpi_slts');
   }

   if ($DB->fieldExists("glpi_slas", "slas_id")) {
      $migration->changeField('glpi_slas', 'slas_id', 'slms_id', 'integer');
      $migration->dropKey('glpi_slas', 'slas_id');
      $migration->addKey('glpi_slas', 'slms_id');
   }

   
   if (!$DB->fieldExists("glpi_slas", "slms_id")) {
      $migration->addField('glpi_slas', 'slms_id', 'integer');
      $migration->addKey('glpi_slas', 'slms_id');
   }
```
##########################

**Comment by kyilmaz80** [comment]
I added the field  slms_id and it works:
`alter table glpi_slas add slms_id INT(11) after id;`
