### ISSUE TITLE
[9.4.x] Slow Performance on Home page

### ISSUE THREAD

**Issue by leeyosee** [glpi-project/glpi#5740]
**Describe the bug**

Takes around 35 seconds to load the Personal (or All) view on Home page.
Looks like big portion of the loading time is on updatecurrenttab.php & common.tabs.php .

**Page(s) URL**

http(s)://glpi-web-url/glpi/front/central.php

**To reproduce**

1. Go to http(s)://glpi-web-url/glpi/front/central.php
2. Watch the view load

**Expected behavior**

Used to take less than 2 seconds loading Personal (or All) view on home page @ version 9.3.x .

**Screenshots**

![image](https://user-images.githubusercontent.com/22165609/55519401-7439b700-562c-11e9-9053-2180c8b4bb9a.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.2 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

[Server]
Operating system: Linux assets-stage.ensemble.com 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64
PHP 7.3.3-1+ubuntu16.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at assets-stage.ensemble.com Port 80)
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.25-0ubuntu0.16.04.2
	Server SQL Mode: 
	Parameters: root@localhost/glpidb
	Host info: Localhost via UNIX socket

[Libraries]
htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

```
**Additional context**

[Patch 5666](https://github.com/glpi-project/glpi/pull/5666.patch) applied.

**Comment by cedric-anne** [comment]
Hi,

Can you use the debug mode, open the `AJAX DEBUG` panel, and look if you have some really slow query that can explain this ?

Regards

**Comment by atanasag** [comment]
I also have very slow overall  performance after upgrade to 9.4.1.1 from 9.4.1.0. I use Windows 2012 IIS and PHP 7.2 with Wincache enabled.

**Comment by atanasag** [comment]
[2019-04-05 16:38:24] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"21@GCS3-5"} 
[2019-04-05 16:38:25] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"36@GCS3-5"} 
[2019-04-05 16:38:30] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"36@GCS3-5"} 
[2019-04-05 16:38:47] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): exif_imagetype(_pictures/da/494_5bcf1b8d5bdda_min.jpg): failed to open stream: No such file or directory
  Backtrace :
  :                                                  
  inc\document.class.php:1545                        exif_imagetype()
  front\document.send.php:72                         Document::isImage()
  {"user":"494@GCS3-5"} 
[2019-04-05 16:38:59] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): exif_imagetype(_pictures/da/494_5bcf1b8d5bdda_min.jpg): failed to open stream: No such file or directory
  Backtrace :
  :                                                  
  inc\document.class.php:1545                        exif_imagetype()
  front\document.send.php:72                         Document::isImage()
  {"user":"494@GCS3-5"} 
[2019-04-05 16:45:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\updatecurrenttab.php:33                       include()
  {"user":"510@GCS3-5"} 
[2019-04-05 16:45:36] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"489@GCS3-5"} 
[2019-04-05 16:45:36] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"489@GCS3-5"} 
[2019-04-05 16:45:42] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"22@GCS3-5"} 
[2019-04-05 16:45:42] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"22@GCS3-5","mem_usage":"0.064\", 1.00Mio)"} 
[2019-04-05 16:45:45] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"36@GCS3-5"} 
[2019-04-05 16:45:54] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"21@GCS3-5"} 
[2019-04-05 16:45:59] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"443@GCS3-5"} 
[2019-04-05 16:46:00] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"510@GCS3-5"} 
[2019-04-05 16:46:02] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"22@GCS3-5"} 
[2019-04-05 16:46:02] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"285@GCS3-5"} 
[2019-04-05 16:46:14] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"21@GCS3-5"} 
[2019-04-05 16:46:14] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"443@GCS3-5"} 
[2019-04-05 16:46:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): exif_imagetype(_pictures/d1/6_5b348f4f4d4d1_min.jpg): failed to open stream: No such file or directory
  Backtrace :
  :                                                  
  inc\document.class.php:1545                        exif_imagetype()
  front\document.send.php:72                         Document::isImage()
  {"user":"6@GCS3-5"} 
[2019-04-05 16:46:24] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  front\document.send.php:33                         include()
  {"user":"6@GCS3-5"} 
[2019-04-05 16:46:24] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): exif_imagetype(_pictures/ba/117_5be01295ab7ba_min.jpg): failed to open stream: No such file or directory
  Backtrace :
  :                                                  
  inc\document.class.php:1545                        exif_imagetype()
  front\document.send.php:72                         Document::isImage()
  {"user":"6@GCS3-5","mem_usage":"0.002\", 1.10Mio)"} 
[2019-04-05 16:47:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"443@GCS3-5"} 
[2019-04-05 16:47:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"181@GCS3-5"} 
[2019-04-05 16:47:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"462@GCS3-5"} 
[2019-04-05 16:47:42] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"22@GCS3-5"} 
[2019-04-05 16:47:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"510@GCS3-5"} 
[2019-04-05 16:47:51] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"489@GCS3-5"} 
[2019-04-05 16:47:51] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"489@GCS3-5","mem_usage":"0.041\", 1.05Mio)"} 
[2019-04-05 16:48:15] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"36@GCS3-5"} 
[2019-04-05 16:49:36] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"489@GCS3-5"} 
[2019-04-05 16:49:39] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"21@GCS3-5"} 
[2019-04-05 16:51:22] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): exif_imagetype(_pictures/da/494_5bcf1b8d5bdda_min.jpg): failed to open stream: No such file or directory
  Backtrace :
  :                                                  
  inc\document.class.php:1545                        exif_imagetype()
  front\document.send.php:72                         Document::isImage()
  {"user":"494@GCS3-5"} 
[2019-04-05 16:51:22] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): exif_imagetype(_pictures/da/494_5bcf1b8d5bdda_min.jpg): failed to open stream: No such file or directory
  Backtrace :
  :                                                  
  inc\document.class.php:1545                        exif_imagetype()
  front\document.send.php:72                         Document::isImage()
  {"user":"494@GCS3-5"} 
[2019-04-05 16:51:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): exif_imagetype(_pictures/da/494_5bcf1b8d5bdda_min.jpg): failed to open stream: No such file or directory
  Backtrace :
  :                                                  
  inc\document.class.php:1545                        exif_imagetype()
  front\document.send.php:72                         Document::isImage()
  {"user":"494@GCS3-5"} 
[2019-04-05 16:51:36] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): exif_imagetype(_pictures/da/494_5bcf1b8d5bdda_min.jpg): failed to open stream: No such file or directory
  Backtrace :
  :                                                  
  inc\document.class.php:1545                        exif_imagetype()
  front\document.send.php:72                         Document::isImage()
  {"user":"494@GCS3-5"} 
[2019-04-05 16:51:45] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): exif_imagetype(_pictures/da/494_5bcf1b8d5bdda_min.jpg): failed to open stream: No such file or directory
  Backtrace :
  :                                                  
  inc\document.class.php:1545                        exif_imagetype()
  front\document.send.php:72                         Document::isImage()
  {"user":"494@GCS3-5"} 
[2019-04-05 16:52:07] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc\session.class.php:616                          
  inc\includes.php:54                                Session::loadLanguage()
  ajax\notifications_ajax.php:33                     include()
  {"user":"285@GCS3-5"} 
[2019-04-05 16:52:26] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): count(): Parameter must be an array or an object that implements Countable
  Backtrace :
  inc\includes.php:101                               
  ajax\notifications_ajax.php:33                     include()
  {"user":"36@GCS3-5"}

**Comment by dyingtako** [comment]
> Hi,
> 
> Can you use the debug mode, open the `AJAX DEBUG` panel, and look if you have some really slow query that can explain this ?
> 
> Regards

Thanks for looking into this.

This is the result we got from `AJAX DEBUG` panel:
24 Queries took 0.038s

Longest query took 0.006s

**Comment by atanasag** [comment]
Hi, 
Ok. I will and will post results here.

**Comment by atanasag** [comment]
/front/ticket.php

6406 Queries took 6.8880000000005s

REQUEST_TIME_FLOAT | => | 1554704429.2534
-- | -- | --
REQUEST_TIME | => | 1554704429

**Comment by cedric-anne** [comment]
Hi,

Chrome profiling will not help, as it will not give us any explaination about the time taken by the server to respond.

I am pretty sure that thoose 6406 queries are related to usage of plugins. Can you try to disable plugins and see if the problem persist? If the problem comes from one plugin in particular, then you should open a bug on plugin repository.

Regards

**Comment by atanasag** [comment]
> Hi,
> 
> Chrome profiling will not help, as it will not give us any explaination about the time taken by the server to respond.
> 
> I am pretty sure that thoose 6406 queries are related to usage of plugins. Can you try to disable plugins and see if the problem persist? If the problem comes from one plugin in particular, then you should open a bug on plugin repository.
> 
> Regards

Hi Cedric
No. We do not use plugins now. This was not happening with previous version with the same environment and no plugins too. We used plugins a long time ago with previous vertions and this performance issues start to happen with new MySQL ver 8.0.12 and PHP 7.3.1. I think its a caching problem but not sure= I have tryed to change PHP ver to 7.2 trough 7.0 and things was worst so I change it back to 7.3 where is is slow but works somehow.

**Comment by cedric-anne** [comment]
@atanasag 

Sorry, I was thinking you were talking about the initial problem of this issue (the performances on the home page).
To have less queries make on ticket page list, try to display less columns or less results.
And do not mix subject please. One issue is for one problem only.

@dyingtako 

We fixed a lot of issues that explains errors you have in your logs. Please try with the [nightly build](https://forge.glpi-project.org/tarballs/9.4-bugfixes.tar.gz) to see if errors re fixed.

**Comment by atanasag** [comment]
Yes we talk for Home screen but for others will post separate issues:
![image](https://user-images.githubusercontent.com/21614115/55712446-7074ae80-59f7-11e9-9ea2-1c9432ad4131.png)

**Comment by orthagh** [comment]
@atanasag in this list, check if one is long ?
If not, how many entities do you have ?

**Comment by atanasag** [comment]
> @atanasag in this list, check if one is long ?
> If not, how many entities do you have ?

No. All of them runs fast - between 0.001 and 0.008
We have 545 Entities

**Comment by tomolimo** [comment]
> > Hi,
> > Chrome profiling will not help, as it will not give us any explaination about the time taken by the server to respond.
> > I am pretty sure that thoose 6406 queries are related to usage of plugins. Can you try to disable plugins and see if the problem persist? If the problem comes from one plugin in particular, then you should open a bug on plugin repository.
> > Regards
> 
> Hi Cedric
> No. We do not use plugins now. This was not happening with previous version with the same environment and no plugins too. We used plugins a long time ago with previous vertions and this performance issues start to happen with new MySQL ver 8.0.12 and PHP 7.3.1. I think its a caching problem but not sure= I have tryed to change PHP ver to 7.2 trough 7.0 and things was worst so I change it back to 7.3 where is is slow but works somehow.

Hello @atanasag,
Are you using Wincache with PHP 7.3?
Just for information, Wincache is not yet compatible with PHP 7.3, but only PHP 7.2. See https://forums.iis.net/t/1239969.aspx?PHP+7+3
Question: where did you get Wincache for PHP 7.3?
Thank you,
Regards,
Tomolimo

**Comment by atanasag** [comment]
> > > Hi,
> > > Chrome profiling will not help, as it will not give us any explaination about the time taken by the server to respond.
> > > I am pretty sure that thoose 6406 queries are related to usage of plugins. Can you try to disable plugins and see if the problem persist? If the problem comes from one plugin in particular, then you should open a bug on plugin repository.
> > > Regards
> > 
> > 
> > Hi Cedric
> > No. We do not use plugins now. This was not happening with previous version with the same environment and no plugins too. We used plugins a long time ago with previous vertions and this performance issues start to happen with new MySQL ver 8.0.12 and PHP 7.3.1. I think its a caching problem but not sure= I have tryed to change PHP ver to 7.2 trough 7.0 and things was worst so I change it back to 7.3 where is is slow but works somehow.
> 
> Hello @atanasag,
> Are you using Wincache with PHP 7.3?
> Just for information, Wincache is not yet compatible with PHP 7.3, but only PHP 7.2. See https://forums.iis.net/t/1239969.aspx?PHP+7+3
> Question: where did you get Wincache for PHP 7.3?
> Thank you,
> Regards,
> Tomolimo
@tomolimo
Hi,
No I dont use wincache i use Zendopcache. If I try to enable APCu with APC backward-compatible extension thing gone worse. It loads very very slow in Assistance and Tickets and Homescreen more than 1 min. if I disable APCu and APC things work just slow 30-40 sec to load some tickets, and 15-20 to load home-screen if i click on a ticket i need to wait 40+ sec to open it. I have tryed to move to PHP 7.2 and use wincache but the things became worst.
Now I'm using latest bug-fixes and my ver is 9.4.2. I was unable to update prior disabling APCu extension.

**Comment by bruce79** [comment]
Just want to let you know, I had the same issues after updating to glpi 9.4.2

https://forum.glpi-project.org/viewtopic.php?id=168971

PHP V7.3.3

Apache:
Server version: Apache/2.4.38 (Win64)
Apache Lounge VC15 Server built:   Feb 28 2019 11:40:54

Zend opcache installed: 7.3.3 (256 MB)
APCU cache 5.1.17 (32MB)

I was able to solve it by updating my php to 7.3.5, released on the 1st of may (zend opcache is included so is also update to 7.3.5)

(Like described it seemed to be a caching issue, no slow query's and the first execution after a refresh was always slow).

Just to let you know.

**Comment by callummoffat** [comment]
Can confirm that upgrading to PHP 7.3.5 has significantly improved GLPI 9.4.2's performance.

Setup:

Operating system: Windows NT WITS01 10.0 build 14393 (Windows Server 2016) AMD64
PHP 7.3.5 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, readline, session, soap, standard, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="32M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.3.14-MariaDB
	Server SQL Mode: 
	Parameters: glpi@127.0.0.1/glpi
	Host info: 127.0.0.1 via TCP/IP

**Comment by atanasag** [comment]
> Can confirm that upgrading to PHP 7.3.5 has significantly improved GLPI 9.4.2's performance. Still takes a bit longer than it used to, but it's within acceptable boundaries.
> 
> Setup:
> 
> Operating system: Windows NT WITS01 10.0 build 14393 (Windows Server 2016) AMD64
> PHP 7.3.5 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, calendar, cgi-fcgi, ctype, curl, date,
> dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
> pdo_mysql, pdo_sqlite, readline, session, soap, standard, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
> Setup: max_execution_time="300" memory_limit="128M" post_max_size="32M" safe_mode="" session.save_handler="files"
> upload_max_filesize="32M"
> Software: Microsoft-IIS/10.0
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
> Server Software: mariadb.org binary distribution
> Server Version: 10.3.14-MariaDB
> Server SQL Mode:
> Parameters: glpi@127.0.0.1/glpi
> Host info: 127.0.0.1 via TCP/IP

I have been trying this and for me, it did not work. For my environment, the only configuration is with PHP 7.2 x64 NTS with WinCache 2.0.0.8 and APCu 5.1.17  and APCubc 1.0.5 that runs reasonably not frustrating.

**Comment by callummoffat** [comment]
Bit worrying that the PHP version is affecting performance this much, though.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by cedric-anne** [comment]
Hi all,

We just merged an improvement that can affect performances on instances with lots of entities.
Could you test applying #5981 to see if it solves your performances issues ?

Regards

**Comment by sidneyveroneze** [comment]
I was having these problems of slowness when using Mysql 8.0.16, while replacing with MariaDB 10.4.6 everything was fixed. I have noticed that some query cache options have been discontinued in this version of MySQL, I believe there is a relation.

**Comment by cedric-anne** [comment]
Maybe we have some redundancy on some queries in homepage which performances are lowered due to query cache removal in MySQL8 (https://mysqlserverteam.com/mysql-8-0-retiring-support-for-the-query-cache/).

**Comment by cedric-anne** [comment]
Hi @dyingtako @atanasag @callummoffat ,

Can you test with current [9.4 nightly](https://forge.glpi-project.org/tarballs/) to see if problem persists ?

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by atanasag** [comment]
Hi again,
This is still an issue even with 9.5.1 I'v updated yesterday.
 I have changed PHP to 7.4 with Wincache 2.0.0.8 everything else **but** Home view and Tickets View works fast.

**Comment by atanasag** [comment]
![image](https://user-images.githubusercontent.com/21614115/93224691-0fb7dc80-f77a-11ea-9eb8-03dd40ff218d.png)
