### ISSUE TITLE
Pictures not displayed - Tickets lost pictures pasted

### ISSUE THREAD

**Issue by dunipj** [glpi-project/glpi#5744]
We noticed that some old tickets lost the pictures that were paste at the follow-up.

User/Tech pictures are not displayed too.

![image](https://user-images.githubusercontent.com/35108492/55588604-956dd680-5704-11e9-81c9-de7d7dcc958b.png)

O tried to find the file, it's at this location:
/glpi/front/document.send.php?file=_pictures/d2/711_59a0566dd1dd2_min.jpg

And in fact looking at the server, it's there, but are not displayed.

![image](https://user-images.githubusercontent.com/35108492/55588662-b3d3d200-5704-11e9-97c8-a54719f053c1.png)

I worried about the images that dissapeared from the tickets. This ticket above had an "pasted" image that is not show.

I think the problem started after the update to the 9.4 version (now i'm using 9.4.1.1).

It's strange because some tickets show the pictures :(

Could someone please help me ?

Tks

**Comment by cedric-anne** [comment]
Hi,

For user pictures, this is fixed by fe903df136950cd26d5e3bb1f2853c9798c65919 (see #5604).

For image not visible in ticket, can you say what is the URL of it ? Could you also check your logs to see if you have any error related to this ?

Regards

**Comment by trasher** [comment]
You should also use the [latest 9.4/bf nightly](https://forge.glpi-project.org/tarballs/) to make sure this is still relevant.

**Comment by dunipj** [comment]
Great about the user pictures, I made the suggested changes and corrected the problem.

I'll try the nightly to see if it solves the problema.

Another ticket example, here should appear an image that was paste with na SSD price.

![image](https://user-images.githubusercontent.com/35108492/55656511-8a32ad80-57cd-11e9-842c-82b865ac0ab8.png)

The image was there on 15 March, so I think the problem happened after the update to 9.4.1.1.

Here are some logs, i tried to do a refresh at the bugged ticket and get the logs, let's see if it helps.

[glpi-bug.txt](https://github.com/glpi-project/glpi/files/3049658/glpi-bug.txt)

Thank you a lot friends ! I'm very worried about losing all the pictures :(

**Comment by cedric-anne** [comment]
Hi,

Is it possible for you to give us an export of the corresponding element from the `glpi_itilfollowups` database table ?

Also, could you check in ``files/_log/*.log` if there is anything related to this missing image ?

Regards

**Comment by dunipj** [comment]
Hi ! 

Sure, I'll send two examples, one file attach files and one with insert pictures.

The first example, ticket 15948. Files were atacched, the process of insert files are at the history log, but the files does not appear.

[15948.txt](https://github.com/glpi-project/glpi/files/3055687/15948.txt)
![15948-files lost](https://user-images.githubusercontent.com/35108492/55746194-87bf9600-5a0f-11e9-9b1c-6cf3f1a4b4ee.png)
![15948-show that files were attach](https://user-images.githubusercontent.com/35108492/55746196-87bf9600-5a0f-11e9-95f1-1b3d64d9624f.png)

**Comment by dunipj** [comment]
The second example, the image was inserted at the follow-up, but at the ticket are not show.

I'll upload a file with the full select and a file a part of the select, the specific follow-up that should show the Picture.

Ticket 17557

[17557 - cut of the follow up part.txt](https://github.com/glpi-project/glpi/files/3055692/17557.-.cut.of.the.follow.up.part.txt)
[17557 - full select.txt](https://github.com/glpi-project/glpi/files/3055693/17557.-.full.select.txt)

**Comment by dunipj** [comment]
I did not find any erros at the suggested logs but i'll send to you too.

[logs.zip](https://github.com/glpi-project/glpi/files/3055718/logs.zip)

**Comment by dunipj** [comment]
Hi,

So, we have both problems ! At the 17557 logs the problem is with images inlined, this problem is the original request.

After, looking another tickets, we discovered problems with documents associated too.

About the ticket id 15948, look at the Picture, no transfer was used, but the associated docs, or the reference to them were lost.

![image](https://user-images.githubusercontent.com/35108492/55831102-bc535080-5ae8-11e9-9deb-cdc31d20966e.png)

**Comment by dunipj** [comment]
I tried to use this /front/document.php, but where can I find a relation to the ticket ?

At this location, the inlined are not show, right ?

**Comment by dunipj** [comment]
I've just updated with the nightly version, but the problem still remains, we lost some inlined images and some attached docs :(

**Comment by dunipj** [comment]
I have other tickets with inlined images lost, should I open another bug request ?

**Comment by dunipj** [comment]
Ticket 17705 - Yesterday I updated to the nightly version - 9.4.2 - I think that after this update it lost

![image](https://user-images.githubusercontent.com/35108492/55955422-cd5ea780-5c37-11e9-8999-9de42aca683c.png)

**Comment by dunipj** [comment]
Ticket - 17867
This is very recent, follow-up from date 09-04 (dd/mm), before yesterday, I made the nightly update yesterday 10-04 (dd/mm), I think that before this update the system lost the reference !


![image](https://user-images.githubusercontent.com/35108492/55955679-68578180-5c38-11e9-9323-6f3c5a289e0f.png)

I'm very worried about losing all inlined images !

**Comment by dunipj** [comment]
Ticket 17867 - SQL Result  - the image should appear at the ID 37014 at the logs bellow.

[17867.txt](https://github.com/glpi-project/glpi/files/3068492/17867.txt)

**Comment by cedric-anne** [comment]
> About the ticket id 15948, look at the Picture, no transfer was used, but the associated docs, or the reference to them were lost.

Tranfer of any item that is not a Ticket leads to losing documents associated to Tickets (fixed in #5703).


> I have other tickets with inlined images lost, should I open another bug request ?

I do not have any idea about why you would lose inlined images. These images are stored in the followup itself, so loosing images without loosing anything else from the followup seems really wird.
When you say "inlined images", are you talking about images pasted inside the rich text editor, or images uploaded using the "file upload" browser feature ?

**Comment by dunipj** [comment]
OK, about the fix #5703 and ticket 15948, this ticket was closed last year ! At date 30-07-2018, I don't understand how it was affected now.

About the second problem, it's really weird, i'm talking about pasted images inside the rich text editor.

**Comment by ladenree76000** [comment]
When user has a profile picture, and log off, picture is deleted. ( this still happens with 9.4.3)
to reproduce : 
go to my profile (/front/user.form.php?id=xxx)
add a picture  OK
check for some followups :  picture is displayed
log off
log in
check for some followups :  picture disappeared
back to  my profile (/front/user.form.php?id=xxx) => no picture


But for other users picture remains until they log in/off

**Comment by trasher** [comment]
@ladenree76000 seems like this ticket was about pasted images in the rich text editor; wht you report is different, please open another ticket.

**Comment by ladenree76000** [comment]
@trasher : you were right. My problem seems resolved with 
https://github.com/glpi-project/glpi/pull/6131
