### ISSUE TITLE
GLPI - mysql query loop setting a SLA in a Solved Ticket causing slowdown

### ISSUE THREAD

**Issue by paulopera** [glpi-project/glpi#6010]
**Description**

If I try to set a SLA in Solved Ticket after I click save it keeps loading and then show a blank screen or something like error 500 (not always). In the end the action is
executed, it sets the desired SLA in the ticket but it’s too slow the role process, taking sometimes 5+ minutes the hole process. If I’m using a chrome window and
do the steps described and then open a new Incognito Window I can use the GLPI normally but the in the normal one I have to wait while it finishes.

**Page(s) URL**

In any solved ticket without SLA.

**To reproduce**

1. Go to a Solved ticket without SLA;
2. Click on Time to Resolve;
3. Set any SLA in the list;
4. Wait "forever" or until it shows an error 500 (not always) or a blank screen.

**Expected behavior**

It should set the SLA almost at real time without a delay or error. I did tried setting a SLA in a Not Solved Ticket and it runs smoothly without errors.

**Logs**

Attached the mysql.log above;
[mysql.log](https://github.com/glpi-project/glpi/files/3277859/mysql.log)
```
Find them in mysql.log files under /var/log/mysql/
```

**Screenshots**

Screenshot 1: You can see the start of the operation as query # 628;
![screenshot 1](https://user-images.githubusercontent.com/7115215/59295138-55255a00-8c59-11e9-91a8-4ed2fd2e5a6c.png)
Screenshot 2: You can see the start of the loop;
![screenshot 2](https://user-images.githubusercontent.com/7115215/59295170-6706fd00-8c59-11e9-8fbc-dd68165c978c.png)

**GLPI setup**

I'm running the GLPI version 9.4.2 on Ubuntu 18.04.2 LTS and both the web and mysql server. Both are up to date too.
I also made a LAB running both GLPI/DB in the same machine and the behavior was the same.
Also did tried running the DB as MariaDB instead of Mysql.

**Additional context**

I've seen this behavior in previous GLPI versions but always thought it was something about my scenario causing this. In the last 2 versions I saw it was more slow than before so I took a look and saw this query loop described above.

**Comment by Armin83** [comment]
I had a different strange bug with sla in the past.

the problem exist when the linked calendar have no working days defined.
I changed calender and solved the problem.

**Comment by paulopera** [comment]
I read something about it but I do have a calendar linked and the working days are defined.

**Comment by cedric-anne** [comment]
Hi @paulopera ,

Not sure of that, but maybe #5805 fixes this problem. Can you try ?

Regards

**Comment by paulopera** [comment]
Thanks for the tip @cedric-anne but it didn't worked, I'm still seeing the query loop in the mysql logs and the slowdown.

**Comment by paulopera** [comment]
@cedric-anne I updated my test GLPI to 9.4.3 using the same DB from my production one and the loop still persists.

**Comment by cedric-anne** [comment]
Hi @paulopera ,

In #6275 , I fixed 2 errors in the calendar class that may have an impact on SLA escalation times computation. The first one was appearing when opening hours of calendar ends at midnight (24:00). For the second one, I do not remember exactly the context.

Can you try this fix ? Maybe your error is related to one of these errors.

Regards

**Comment by paulopera** [comment]
@cedric-anne It didn't fix the problem. It still persists the loop in Solved Tickets when I set any SLA

**Comment by paulopera** [comment]
I know it's not related to this thread but when the search criteria status not solved and SLA time to resolve is/is not set the page shows an error with the debug and if I execute the search the page doesn't shows up.
![image](https://user-images.githubusercontent.com/7115215/87788497-dadbe780-c813-11ea-96bb-66f611136d3b.png)

**Comment by paulopera** [comment]
Here's what the debug mode display when I set the search criteria either **is** and **is not**:

![image](https://user-images.githubusercontent.com/7115215/88464369-7c0c1300-ce90-11ea-994b-b024ee938e88.png)

Here when the SLA Time to Resolve condition is set to **is**
[2020-07-25 15:59:56] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Dropdown::addNewCondition() must be of the type array, string given, called in /usr/share/glpi/inc/dropdown.class.php on line 157 in /usr/share/glpi/inc/dropdown.class.php at line 278
  Backtrace :
  inc/dropdown.class.php:157                         Dropdown::addNewCondition()
  inc/commondbtm.class.php:3916                      Dropdown::show()
  inc/commondbtm.class.php:4837                      CommonDBTM::dropdown()
  inc/ticket.class.php:6789                          CommonDBTM->getValueToSelect()
  inc/search.class.php:3017                          Ticket->getValueToSelect()
  ajax/search.php:62                                 Search::displaySearchoptionValue()

Here when the SLA Time to Resolve condition is set to **is not**
[2020-07-25 15:59:59] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Dropdown::addNewCondition() must be of the type array, string given, called in /usr/share/glpi/inc/dropdown.class.php on line 157 in /usr/share/glpi/inc/dropdown.class.php at line 278
  Backtrace :
  inc/dropdown.class.php:157                         Dropdown::addNewCondition()
  inc/commondbtm.class.php:3916                      Dropdown::show()
  inc/commondbtm.class.php:4837                      CommonDBTM::dropdown()
  inc/ticket.class.php:6789                          CommonDBTM->getValueToSelect()
  inc/search.class.php:3017                          Ticket->getValueToSelect()
  ajax/search.php:62                                 Search::displaySearchoptionValue()

**Comment by cedric-anne** [comment]
Hi @paulopera,

> [2020-07-25 15:59:56] glpiphplog.CRITICAL: *** Uncaught Exception TypeError: Argument 1 passed to Dropdown::addNewCondition() must be of the type array, string given, called in /usr/share/glpi/inc/dropdown.class.php on line 157 in /usr/share/glpi/inc/dropdown.class.php at line 278
> Backtrace :
> inc/dropdown.class.php:157 Dropdown::addNewCondition()
> inc/commondbtm.class.php:3916 Dropdown::show()
> inc/commondbtm.class.php:4837 CommonDBTM::dropdown()
> inc/ticket.class.php:6789 CommonDBTM->getValueToSelect()
> inc/search.class.php:3017 Ticket->getValueToSelect()
> ajax/search.php:62 Search::displaySearchoptionValue()

This issue should be fixed by #7768 

For the main issue of this thread, did you tried with GLPI 9.5 ? We recently fixed an issue that was causing an infinite loop when using a calendar that has no opening days.

Regards

**Comment by paulopera** [comment]
Hi @cedric-anne , thanks for the update and yes the fix solved the main problem. Now when I set a SLA it doesn't trigger the loop! 
Do you recommend that I open a new issue for the other issue I reported?
Thank you so much for all the help!

**Comment by cedric-anne** [comment]
> Hi @cedric-anne , thanks for the update and yes the fix solved the main problem. Now when I set a SLA it doesn't trigger the loop!
> Do you recommend that I open a new issue for the other issue I reported?
> Thank you so much for all the help!

Yes, you should open another issue, and describe all steps to reproduce.

Regards

**Comment by paulopera** [comment]
As [mentioned](https://github.com/glpi-project/glpi/issues/6010#issuecomment-664181373) by @cedric-anne the issue was solved with the update 9.5.1.

**Comment by paulopera** [comment]
@cedric-anne I'm so sorry! The loop still persists if the ticket SOLVED and I try to set a SLA to the ticket.
When I answered and closed the issue an hour ago I did the test with an open ticket and not with a solved one which was the main problem with this action.
The mysql.log displays the same as in the OP:
`2020-07-27T13:24:25.506606Z	  223 Query	SELECT `glpi_slalevels_tickets`.* FROM `glpi_slalevels_tickets` LEFT JOIN `glpi_slalevels` ON (`glpi_slalevels_tickets`.`slalevels_id` = `glpi_slalevels`.`id`) LEFT JOIN `glpi_slas` ON (`glpi_slalevels`.`slas_id` = `glpi_slas`.`id`) WHERE `glpi_slalevels_tickets`.`date` < NOW() AND `glpi_slalevels_tickets`.`tickets_id` = '24404' AND `glpi_slas`.`type` = '0'
2020-07-27T13:24:25.508374Z	  223 Query	SELECT * FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = '24404' LIMIT 1
2020-07-27T13:24:25.508821Z	  223 Query	SELECT * FROM `glpi_groups_tickets` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.509141Z	  223 Query	SELECT * FROM `glpi_tickets_users` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.510116Z	  223 Query	SELECT * FROM `glpi_suppliers_tickets` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.510670Z	  223 Query	SELECT `glpi_slalevels_tickets`.* FROM `glpi_slalevels_tickets` LEFT JOIN `glpi_slalevels` ON (`glpi_slalevels_tickets`.`slalevels_id` = `glpi_slalevels`.`id`) LEFT JOIN `glpi_slas` ON (`glpi_slalevels`.`slas_id` = `glpi_slas`.`id`) WHERE `glpi_slalevels_tickets`.`date` < NOW() AND `glpi_slalevels_tickets`.`tickets_id` = '24404' AND `glpi_slas`.`type` = '0'
2020-07-27T13:24:25.511258Z	  223 Query	SELECT * FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = '24404' LIMIT 1
2020-07-27T13:24:25.513372Z	  223 Query	SELECT * FROM `glpi_groups_tickets` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.514554Z	  223 Query	SELECT * FROM `glpi_tickets_users` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.515193Z	  223 Query	SELECT * FROM `glpi_suppliers_tickets` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.516365Z	  223 Query	SELECT `glpi_slalevels_tickets`.* FROM `glpi_slalevels_tickets` LEFT JOIN `glpi_slalevels` ON (`glpi_slalevels_tickets`.`slalevels_id` = `glpi_slalevels`.`id`) LEFT JOIN `glpi_slas` ON (`glpi_slalevels`.`slas_id` = `glpi_slas`.`id`) WHERE `glpi_slalevels_tickets`.`date` < NOW() AND `glpi_slalevels_tickets`.`tickets_id` = '24404' AND `glpi_slas`.`type` = '0'
2020-07-27T13:24:25.517226Z	  223 Query	SELECT * FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = '24404' LIMIT 1
2020-07-27T13:24:25.517821Z	  223 Query	SELECT * FROM `glpi_groups_tickets` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.518275Z	  223 Query	SELECT * FROM `glpi_tickets_users` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.518873Z	  223 Query	SELECT * FROM `glpi_suppliers_tickets` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.519395Z	  223 Query	SELECT `glpi_slalevels_tickets`.* FROM `glpi_slalevels_tickets` LEFT JOIN `glpi_slalevels` ON (`glpi_slalevels_tickets`.`slalevels_id` = `glpi_slalevels`.`id`) LEFT JOIN `glpi_slas` ON (`glpi_slalevels`.`slas_id` = `glpi_slas`.`id`) WHERE `glpi_slalevels_tickets`.`date` < NOW() AND `glpi_slalevels_tickets`.`tickets_id` = '24404' AND `glpi_slas`.`type` = '0'
2020-07-27T13:24:25.520030Z	  223 Query	SELECT * FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = '24404' LIMIT 1
2020-07-27T13:24:25.520572Z	  223 Query	SELECT * FROM `glpi_groups_tickets` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.520993Z	  223 Query	SELECT * FROM `glpi_tickets_users` WHERE `tickets_id` = '24404' ORDER BY `id` ASC
2020-07-27T13:24:25.521374Z	  223 Query	SELECT * FROM `glpi_suppliers_tickets` WHERE `tickets_id` = '24404' ORDER BY `id` ASC`

**Comment by paulopera** [comment]
Running the version 9.5.5 and the issue is still happening.

**Comment by paulopera** [comment]
Running the version 9.5.6 and the issue is still happening.

**Comment by paulopera** [comment]
Running the version 9.5.6 and the issue is still happening.

**Comment by cedric-anne** [comment]
@paulopera 

Could you take a look at #10914 ?

**Comment by paulopera** [comment]
Hi @cedric-anne I tried and here the result:
When I set the SLA and press SAVE the screen goes blank:
![Screen Shot 2022-03-09 at 08 38 40](https://user-images.githubusercontent.com/7115215/157434932-532dedc2-3110-41f5-b5e2-386c9b473329.png)

And in the glpi logs shows:
[Wed Mar 09 08:38:21.514754 2022] [php7:notice] [pid 2729515] [client 192.168.0.219:61547] PHP Notice:  Trying to access array offset on value of type null in /usr/share/glpi/inc/slalevel_ticket.class.php on line 348, referer: https://suporte.avare.sp.gov.br/front/ticket.form.php?id=28547&forcetab=Ticket$2

If I refresh the page it displays "The action you have requested is not allowed" 
![Screen Shot 2022-03-09 at 08 41 12](https://user-images.githubusercontent.com/7115215/157436023-a76413ea-6053-4707-83f3-74b78b971cc7.png)

![Screen Shot 2022-03-09 at 08 41 09](https://user-images.githubusercontent.com/7115215/157436044-de439501-7cac-4cbd-9082-2457674c7316.png)

And then I press "Back" is comes to the ticket page:
![Screen Shot 2022-03-09 at 08 41 20](https://user-images.githubusercontent.com/7115215/157435739-760f5473-5fdb-4389-823b-5ee785006b5f.png)

**Comment by cedric-anne** [comment]
In GLPI 9.5, `$data = $iterator->next();` must be used instead of `$data = $iterator->current();`. The encountered issue may be due to this if you copied the entire file/method contents.

**Comment by cconard96** [comment]
It should close automatically after the change is approved and merged.
