### ISSUE TITLE
mail receivers not working

### ISSUE THREAD

**Issue by martin-crockett** [glpi-project/glpi#7683]
**Expected behavior**

after updating to 9.5.0 mail receivers doesnt work i tried updating with the 9.5 bugfixes and still doesnt work.

i tried every option, pop,imap, ssl, no ssl, port 143,port 993, port 995, tls, no tls, domain name, server ip, localhost.. nothing work.

when i click get 'get email tickets now" im redirected to a blank page (https://domain.ca/glpi/front/mailcollector.form.php) and nothing happens
![image](https://user-images.githubusercontent.com/45770116/87443104-0e740300-c5c3-11ea-86e4-ccecb8cf7fdd.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

  GLPI 9.5.0 (/glpi => /home/domain/public_html/glpi) Installation mode: TARBALL
--


[code]   GLPI 9.5.0 (/glpi => /home/domain/public_html/glpi) Installation mode: TARBALL
--

Operating system: Linux odedi56318.mywhc.ca 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64 PHP 7.4.7 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, SourceGuardian, Zend OPcache, apcu, bcmath, bz2, 	calendar, cgi-fcgi, ctype, curl, date, dba, dom, enchant, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, 	imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcntl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, 	posix, pspell, session, shmop, snmp, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="60" memory_limit="256M" post_max_size="128M" safe_mode="" session.save_handler="files" 	upload_max_filesize="128M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.2.32-MariaDB 	Server SQL Mode:  	Parameters: domain_glpi32@localhost/domain_glpi32 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is not present Database version seems correct (10.2.32) - Perfect! Access to timezone database (mysql) is not allowed. The log file has been created successfully. Write access to /home/domain/public_html/glpi/config has been validated. Write access to /home/domain/public_html/glpi/files has been validated. Write access to /home/domain/public_html/glpi/files/_dumps has been validated. Write access to /home/domain/public_html/glpi/files/_sessions has been validated. Write access to /home/domain/public_html/glpi/files/_cron has been validated. Write access to /home/domain/public_html/glpi/files/_graphs has been validated. Write access to /home/domain/public_html/glpi/files/_lock has been validated. Write access to /home/domain/public_html/glpi/files/_plugins has been validated. Write access to /home/domain/public_html/glpi/files/_tmp has been validated. Write access to /home/domain/public_html/glpi/files/_cache has been validated. Write access to /home/domain/public_html/glpi/files/_rss has been validated. Write access to /home/domain/public_html/glpi/files/_uploads has been validated. Write access to /home/domain/public_html/glpi/files/_pictures has been validated. Write access to /home/domain/public_html/glpi/marketplace has been validated. Web access to files directory is protected For security reasons, SELinux mode should be Enforcing.

GLPI_ROOT: /home/domain/public_html/glpi GLPI_CONFIG_DIR: /home/domain/public_html/glpi/config GLPI_VAR_DIR: /home/domain/public_html/glpi/files GLPI_MARKETPLACE_DIR: /home/domain/public_html/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_FORCE_NATIVE_SQL_TYPES: 1 GLPI_DOC_DIR: /home/domain/public_html/glpi/files GLPI_CACHE_DIR: /home/domain/public_html/glpi/files/_cache GLPI_CRON_DIR: /home/domain/public_html/glpi/files/_cron GLPI_DUMP_DIR: /home/domain/public_html/glpi/files/_dumps GLPI_GRAPH_DIR: /home/domain/public_html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /home/domain/public_html/glpi/files/_locales GLPI_LOCK_DIR: /home/domain/public_html/glpi/files/_lock GLPI_LOG_DIR: /home/domain/public_html/glpi/files/_log GLPI_PICTURE_DIR: /home/domain/public_html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /home/domain/public_html/glpi/files/_plugins GLPI_RSS_DIR: /home/domain/public_html/glpi/files/_rss GLPI_SESSION_DIR: /home/domain/public_html/glpi/files/_sessions GLPI_TMP_DIR: /home/domain/public_html/glpi/files/_tmp GLPI_UPLOAD_DIR: /home/domain/public_html/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /home/domain/public_html/glpi/locales GLPI_VERSION: 9.5.0 GLPI_SCHEMA_VERSION: 9.5.0 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020 GLPI_MOD_DIR: /home/domain/public_html/glpi/plugins/mod

htmlawed/htmlawed version 1.2.5 in (/home/domain/public_html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/home/domain/public_html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.5 in (/home/domain/public_html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/home/domain/public_html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/home/domain/public_html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/home/domain/public_html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/home/domain/public_html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/home/domain/public_html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/home/domain/public_html/glpi/vendor/sabre/http/lib) sabre/uri in (/home/domain/public_html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/home/domain/public_html/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/home/domain/public_html/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/home/domain/public_html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/home/domain/public_html/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/home/domain/public_html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/home/domain/public_html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/home/domain/public_html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/home/domain/public_html/glpi/vendor/symfony/console) scssphp/scssphp in (/home/domain/public_html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/home/domain/public_html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/home/domain/public_html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/home/domain/public_html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/home/domain/public_html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/home/domain/public_html/glpi/vendor/ramsey/uuid/src) psr/log in (/home/domain/public_html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/home/domain/public_html/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/home/domain/public_html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/home/domain/public_html/glpi/vendor/guzzlehttp/guzzle/src) wapmorgan/unified-archive in (/home/domain/public_html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/home/domain/public_html/glpi/vendor/paragonie/sodium_compat/src)

Not active

Way of sending emails: PHP

Name: 'support@domain.ca' Active: Yes 	Server: '{domain.ca:993/imap/ssl/notls/debug}INBOX' Login: 'support@domain.ca' Password: Yes

accounts             Name: Accounts                       Version: 2.5.0      State: Installed / not activated 	fields               Name: Additional Fields              Version: 1.11.0     State: Enabled 	dashboard            Name: Dashboard                      Version: 0.9.7      State: Installed / not activated 	databases            Name: Databases                      Version: 2.2.0      State: Installed / not activated 	domains              Name: Domains                        Version: 2.1.0      State: Installed / not activated 	environment          Name: Environment                    Version: 2.3.0      State: Installed / not activated 	datainjection        Name: File injection                 Version: 2.7.0      State: Installed / not activated 	formcreator          Name: Forms                          Version: 2.7.0      State: Installed / not activated 	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled 	mod                  Name: GLPI Modifications             Version: 1.5.2      State: Enabled 	resources            Name: Human Resources                Version: 2.6.0      State: Installed / not activated 	mydashboard          Name: My Dashboard                   Version: 1.7.4      State: Installed / not activated 	officeonline         Name: Office Online                  Version: 1.0.1      State: Installed / not activated 	reservation          Name: Reservation                    Version: 2.2.0      State: Installed / not activated 	shellcommands        Name: Shell Commands                 Version: 2.3.0      State: Installed / not activated 	showconns            Name: Show connected items           Version: 0.1        State: Installed / not activated 	webapplications      Name: Web applications               Version: 2.6.0      State: Installed / not activated
[/code]

**Comment by martin-crockett** [comment]
log

[2020-07-14 11:55:57] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\RuntimeException: cannot login, user or password wrong in /home/expertba/public_html/glpi/vendor/laminas/laminas-mail/src/Storage/Imap.php at line 218
  Backtrace :
  inc/toolbox.class.php:2323                         Laminas\Mail\Storage\Imap->__construct()
  inc/mailcollector.class.php:1282                   Toolbox::getMailServerStorageInstance()
  inc/mailcollector.class.php:663                    MailCollector->connect()
  front/mailcollector.form.php:77                    MailCollector->collect()

**Comment by martin-crockett** [comment]
log
[2020-07-14 12:24:43] glpiphplog.ERROR: MailCollector::collect() in /home/expertba/public_html/glpi/inc/mailcollector.class.php line 665
#0 /home/domain/public_html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php(176): Laminas\Mail\Protocol\Imap->nextLine()
#1 /home/domain/public_html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php(138): Laminas\Mail\Protocol\Imap->assumedNextLine('* OK')
#2 /home/domain/public_html/glpi/vendor/laminas/laminas-mail/src/Storage/Imap.php(216): Laminas\Mail\Protocol\Imap->connect('domain....', '993', false)
#3 /home/domain/public_html/glpi/inc/toolbox.class.php(2324): Laminas\Mail\Storage\Imap->__construct(Object(stdClass))
#4 /home/domain/public_html/glpi/inc/mailcollector.class.php(1282): Toolbox::getMailServerStorageInstance('imap', Array)
#5 /home/domain/public_html/glpi/inc/mailcollector.class.php(663): MailCollector->connect()
#6 /home/domain/public_html/glpi/front/mailcollector.form.php(77): MailCollector->collect('9', 1)

**Comment by martin-crockett** [comment]
then i try a brand new install on an other domain on the same dedicated server.
and i have an other error

[2020-07-14 17:44:02] glpiphplog.CRITICAL:   *** Uncaught Exception SodiumException: Key must be CRYPTO_AEAD_XCHACHA20POLY1305_KEYBYTES long in /home/expertpro/public_html/glpi/vendor/paragonie/sodium_compat/src/Compat.php at line 897
  Backtrace :
  ...paragonie/sodium_compat/lib/php72compat.php:350 ParagonIE_Sodium_Compat::crypto_aead_xchacha20poly1305_ietf_encrypt()
  inc/toolbox.class.php:272                          sodium_crypto_aead_xchacha20poly1305_ietf_encrypt()
  inc/mailcollector.class.php:141                    Toolbox::sodiumEncrypt()
  inc/mailcollector.class.php:168                    MailCollector->prepareInput()
  inc/commondbtm.class.php:1099                      MailCollector->prepareInputForAdd()
  front/mailcollector.form.php:48                    CommonDBTM->add()

**Comment by trasher** [comment]
Several issues has been fixed since the release regarding collectors. Please try with [latest nightly build](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)

**Comment by martin-crockett** [comment]
still not working, 

Uncaught Exception Laminas\Mail\Storage\Exception\RuntimeException: cannot login, user or password wrong in /home/expertba/public_html/glpi/vendor/laminas/laminas-mail/src/Storage/Imap.php at line 218

**Comment by cedric-anne** [comment]
#7698 may prevent the blank page, but message is pretty clear "cannot login, user or password wrong".

Had you a working configuration before upgrading to GLPI 9.5 ? What was this configuration ?

Regards

**Comment by martin-crockett** [comment]
login an password is correct, yes it was working before. 

[code]   GLPI 9.4.6 (/glpi => /home/domain/public_html/glpi) Installation mode: TARBALL
--

Operating system: Linux odedi56318.mywhc.ca 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 PHP 7.4.8 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, SourceGuardian, Zend OPcache, apcu, bcmath, bz2, 	calendar, cgi-fcgi, ctype, curl, date, dba, dom, enchant, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, 	imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcntl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, 	posix, pspell, session, shmop, snmp, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="60" memory_limit="256M" post_max_size="128M" safe_mode="" session.save_handler="files" 	upload_max_filesize="128M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.2.32-MariaDB 	Server SQL Mode:  	Parameters: domain_glpi32@localhost/domain_glpi32 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed exif extension is installed CAS extension is not present Database version seems correct (10.2.32) - Perfect! /home/domain/public_html/glpi/files/_log : OK /home/domain/public_html/glpi/config : OK /home/domain/public_html/glpi/files : OK /home/domain/public_html/glpi/files/_dumps : OK /home/domain/public_html/glpi/files/_sessions : OK /home/domain/public_html/glpi/files/_cron : OK /home/domain/public_html/glpi/files/_graphs : OK /home/domain/public_html/glpi/files/_lock : OK /home/domain/public_html/glpi/files/_plugins : OK /home/domain/public_html/glpi/files/_tmp : OK /home/domain/public_html/glpi/files/_cache : OK /home/domain/public_html/glpi/files/_rss : OK /home/domain/public_html/glpi/files/_uploads : OK /home/domain/public_html/glpi/files/_pictures : OK Web access to files directory is protected : OK SELinux mode is Unknown SELinux boolean configuration for httpd_can_network_connect --> unkwown (Some features may require this to be on) SELinux boolean configuration for httpd_can_network_connect_db --> unkwown (Some features may require this to be on) SELinux boolean configuration for httpd_can_sendmail --> unkwown (Some features may require this to be on)

htmLawed version 1.2.4 in (/home/domain/public_html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/home/domain/public_html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.3 in (/home/domain/public_html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.2 in (/home/domain/public_html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/home/domain/public_html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/home/domain/public_html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/home/domain/public_html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/home/domain/public_html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/home/domain/public_html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/home/domain/public_html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/home/domain/public_html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/home/domain/public_html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/home/domain/public_html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/home/domain/public_html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/home/domain/public_html/glpi/vendor/symfony/console) leafo/scssphp in (/home/domain/public_html/glpi/vendor/leafo/scssphp/src)


Not active

Way of sending emails: PHP

Name: 'support@domain.ca' Active: Yes 	Server: '{domain.ca/imap/ssl/novalidate-cert/notls/debug}INBOX' Login: 'support@domain.ca' Password: Yes

accounts             Name: Accounts                       Version: 2.5.0      State: Not activated 	fields               Name: Additional Fields              Version: 1.10.0     State: Enabled 	dashboard            Name: Dashboard                      Version: 0.9.7      State: Not activated 	databases            Name: Databases                      Version: 2.2.0      State: Not activated 	domains              Name: Domains                        Version: 2.1.0      State: Not activated 	environment          Name: Environment                    Version: 2.3.0      State: Not activated 	datainjection        Name: File injection                 Version: 2.7.0      State: Not activated 	formcreator          Name: Forms                          Version: 2.7.0      State: Not activated 	fusioninventory      Name: FusionInventory                Version: 9.4+2.4    State: Enabled 	mod                  Name: GLPI Modifications             Version: 1.5.2      State: Enabled 	resources            Name: Human Resources                Version: 2.6.0      State: Not activated 	mydashboard          Name: My Dashboard                   Version: 1.7.4      State: Not activated 	officeonline         Name: Office Online                  Version: 1.0.1      State: Not activated 	reservation          Name: Reservation                    Version: 2.2.0      State: Enabled 	shellcommands        Name: Shell Commands                 Version: 2.3.0      State: Not activated 	showconns            Name: Show connected items           Version: 0.1        State: Not activated 	webapplications      Name: Web applications               Version: 2.6.0      State: Not activated
[/code]

**Comment by cedric-anne** [comment]
> Had you a working configuration before upgrading to GLPI 9.5 ? What was this configuration ?

I was refering to the mail collector configuration. Can you give use its connection params (pop, imap, ssl, no ssl, port 143,port 993, port 995, tls, no tls, etc) ?
Maybe one of these option is not working properly on 9.5.

**Comment by martin-crockett** [comment]
![image](https://user-images.githubusercontent.com/45770116/87793438-470a1b80-c813-11ea-97e2-fffba305e4ac.png)
port 993

**Comment by cedric-anne** [comment]
Your problem may be due to usage of the "no-validate-cert" option. See #7693.

**Comment by martin-crockett** [comment]
now, when i test on a new installation on an other domain name on the same dedicated server i have an other error message when i try to add a mail receiver

Uncaught Exception SodiumException: Key must be CRYPTO_AEAD_XCHACHA20POLY1305_KEYBYTES long in /home/expertpro/public_html/glpi/vendor/paragonie/sodium_compat/src/Compat.php at line 897

**Comment by cedric-anne** [comment]
> now, when i test on a new installation on an other domain name on the same dedicated server i have an other error message when i try to add a mail receiver
> 
> Uncaught Exception SodiumException: Key must be CRYPTO_AEAD_XCHACHA20POLY1305_KEYBYTES long in /home/expertpro/public_html/glpi/vendor/paragonie/sodium_compat/src/Compat.php at line 897

Please provide the full stack trace. Wihout it, we cannot really investigate.

**Comment by martin-crockett** [comment]
Toolbox::sodiumEncrypt()
  
[2020-07-21 13:57:59] glpiphplog.CRITICAL:   *** Uncaught Exception SodiumException: Key must be CRYPTO_AEAD_XCHACHA20POLY1305_KEYBYTES long in /home/test/public_html/glpi/vendor/paragonie/sodium_compat/src/Compat.php at line 897
  Backtrace :
  ...paragonie/sodium_compat/lib/php72compat.php:350 ParagonIE_Sodium_Compat::crypto_aead_xchacha20poly1305_ietf_encrypt()
  inc/toolbox.class.php:272                          sodium_crypto_aead_xchacha20poly1305_ietf_encrypt()
  ajax/mailcollector.php:61                          Toolbox::sodiumEncrypt()

**Comment by cedric-anne** [comment]
It looks like your GLPI key is corrupted, I do not know how it is possible. Did you edit the `config/glpi.key` file ?

**Comment by martin-crockett** [comment]
no i have not, never

**Comment by ricardoamedeiros** [comment]
I'm having trouble logging into Exchange. The application connects, but gives a user and password error even without using special characters. The problem does not happen at office365. In version 9.4.6 the same configuration works. I have already changed the password several times and it was no use. I am not using TSL.

![image](https://user-images.githubusercontent.com/37345163/90312079-fc45f700-ded7-11ea-9d2e-eda2da2eea72.png)

**Comment by ricardoamedeiros** [comment]
> It looks like your GLPI key is corrupted, I do not know how it is possible. Did you edit the `config/glpi.key` file ?
That is not the problem. In office365 IMAP works, but in exchange it doesn't work.

**Comment by ricardoamedeiros** [comment]
> It looks like your GLPI key is corrupted, I do not know how it is possible. Did you edit the `config/glpi.key` file ?

That is not the problem. In office365 IMAP works, but in exchange it doesn't work.

**Comment by cedric-anne** [comment]
> now, when i test on a new installation on an other domain name on the same dedicated server i have an other error message when i try to add a mail receiver
> 
> Uncaught Exception SodiumException: Key must be CRYPTO_AEAD_XCHACHA20POLY1305_KEYBYTES long in /home/test/public_html/glpi/vendor/paragonie/sodium_compat/src/Compat.php at line 897

If I understand right, you have no `config/glpicrypt.key` on your server. This should not happen, and you should run `bin/console glpi:security:change_key` to generate a new key.

**Comment by cedric-anne** [comment]
@ricardoamedeiros 

> I'm having trouble logging into Exchange. The application connects, but gives a user and password error even without using special characters. The problem does not happen at office365. In version 9.4.6 the same configuration works. I have already changed the password several times and it was no use. I am not using TSL.
> 
> ![image](https://user-images.githubusercontent.com/37345163/90312079-fc45f700-ded7-11ea-9d2e-eda2da2eea72.png)

Initial issue does not mention the `exchange` keyword, so, please, open another issue and give all requested informations if you want us to be able to take a look at it in the best conditions.

Regards

**Comment by cedric-anne** [comment]
Hi,

Multiple problems related to encryption and mail receivers have been solved recently. I close this issue  as no feedback were given to latests comments. Feel free to reopen if problem persist or open a new issue if a new problem appears.

Regards
