### ISSUE TITLE
Mailgate encoding error (9.5.0 & 9.5.1)

### ISSUE THREAD

**Issue by sazanof** [glpi-project/glpi#7709]
Hi! Its a bug? 
We have a mail collector since 9.x.x versions. And everything worked fine. But when I upgrade glpi to 9.5.0, mailgate task send email witn wrong encoding. After that I upgraded to 9.5.1, but problem still remains
![image](https://user-images.githubusercontent.com/3595562/87684793-55145980-c78b-11ea-9a78-47e79d4abee2.png)
emails with incorrect encoding (only body) are also sent to your email address
 no errors in logs, 
eml file
[eml.txt](https://github.com/glpi-project/glpi/files/4932169/eml.txt)
system info
[sysinfo.txt](https://github.com/glpi-project/glpi/files/4932195/sysinfo.txt)

**Comment by trasher** [comment]
This sounds like a bug yes.

Unfortunately, the provided eml file does not work in our tests suite; seems there is an issue in the headers (date is present, but cannot be found). Could you please check the uploaded file is correct?

**Comment by sazanof** [comment]
yea, this is correct eml

[[GLPI #1710313213] New Ticket тест2.zip](https://github.com/glpi-project/glpi/files/4932567/GLPI.1710313213.New.Ticket.2.zip)

**Comment by trasher** [comment]
This one works, thanks :)

**Comment by trasher** [comment]
Maybe I have answered a bit too fast... In facts, I'm not able to import this message (it's well formatted now, but this seems to be a notification email sent from GLPI, those kind of emails are blacklisted at import).

I've just tried with a content of mine contains french and cyrillic characters, I've not reproduced the issue; so there is something in the email itself that make things goes wrong.

I've spent more than an hour trying to reproduce without succes. We'll need the original email that was collected.

**Comment by sazanof** [comment]
[emls.zip](https://github.com/glpi-project/glpi/files/4936300/emls.zip)
Hello! Look, this is emails that send to server mailbox-collector. Note, that one of them delivered later (to glpi & to admin addresses) CORRECTLY (this-is-correct-from-iphone.eml)!
![image](https://user-images.githubusercontent.com/3595562/87759936-bb46be00-c817-11ea-873c-220f91d2b76b.png)

**Comment by sazanof** [comment]
The difference is, that in correct email body is in base64
![image](https://user-images.githubusercontent.com/3595562/87760509-81c28280-c818-11ea-892d-34f4a96235be.png)
I.DON`T.KNOW

**Comment by trasher** [comment]
Not sure this is the base64, the working one uses UTF-8, while others don't (windows-1251 and koi8-r); that also may be the cause.

I'll try with new provided data, thank you.

**Comment by trasher** [comment]
So, I've been able to import one of those, but I'm absolutely not sure about the results. I'm lost with all those headers, encodings, and also with html/non html: I really do not know what to expect.
I've already spent hours on that without results, I give up.

**Comment by sazanof** [comment]
I`ll try to understand to what happens, but the problem exists =)

**Comment by neutrolino** [comment]
I confirm the same issue after upgrading from 9.4.6 to 9.5.1
![изображение](https://user-images.githubusercontent.com/68535525/87912962-f85cbb80-ca76-11ea-874a-ace556b6b21e.png)

**Comment by bubsik** [comment]
I confirm the same issue with KOI8-R charset in mailcollector.php after upgrading from 9.4.6 to 9.5.1
![image](https://user-images.githubusercontent.com/68593210/88048768-99717200-cb5c-11ea-9154-687ce5743eb5.png)

**Comment by cedric-anne** [comment]
Hi,

Can you try to apply commit 124a435f10a38b6c942acb28bf2a413d9170bc65 ? I tried to reproduce the 9.4 logic on content decoding.

Regards

**Comment by bubsik** [comment]
> Hi,
> 
> Can you try to apply commit [124a435](https://github.com/glpi-project/glpi/commit/124a435f10a38b6c942acb28bf2a413d9170bc65) ? I tried to reproduce the 9.4 logic on content decoding.
> 
> Regards

Dear Cedric I downlaod this file https://github.com/glpi-project/glpi/blob/124a435f10a38b6c942acb28bf2a413d9170bc65/inc/mailcollector.class.php and replace my current mailcollector.class.php but problem still same

![image](https://user-images.githubusercontent.com/68593210/88074073-9e93e880-cb7f-11ea-94d9-b49b2071c32a.png)

**Comment by lustiness** [comment]
Hello! found a solution to the problem?

**Comment by cedric-anne** [comment]
Hi,

I just updated #7748. I was now able to made tests locally and encoding seems correct to me.

Regards

**Comment by bubsik** [comment]
> Hi,
> 
> I just updated #7748. I was now able to made tests locally and encoding seems correct to me.
> 
> Regards

I confirm fixed file work fine, for me problem is solved. Thank you!

**Comment by sazanof** [comment]
@cedric-anne hello! Yes, your commit is fixed the issue. I replace only one file named mailcollector.class.php, and encoding of russian email became correct! Thank you very much!

**Comment by gcastellarin** [comment]
Hello, i replace the file mailcollector.class.php with the last commit (17bc1ec ) but the problem still the same when email is sending by outlook in HTML.  The Image content in the body don't appear. When the same email is send with webmail the contetn appear correctly.
![image](https://user-images.githubusercontent.com/68955902/88805134-116c1780-d1af-11ea-983f-ba262f33d31e.png)

![image](https://user-images.githubusercontent.com/68955902/88805260-33fe3080-d1af-11ea-8a23-9f877d05ea43.png)

What can i do now???
Thanks

**Comment by cedric-anne** [comment]
> Hello, i replace the file mailcollector.class.php with the last commit ([17bc1ec](https://github.com/glpi-project/glpi/commit/17bc1ec17e75c176a68de7a411f1e2a85bc96dfc) ) but the problem still the same when email is sending by outlook in HTML. The Image content in the body don't appear. When the same email is send with webmail the contetn appear correctly.
> ![image](https://user-images.githubusercontent.com/68955902/88805134-116c1780-d1af-11ea-983f-ba262f33d31e.png)
> 
> ![image](https://user-images.githubusercontent.com/68955902/88805260-33fe3080-d1af-11ea-8a23-9f877d05ea43.png)
> 
> What can i do now???
> Thanks

Hi,

Please open another issue. Your issues seems different from the one discussed on this thread.
To help us debugging, please export your email into eml format and attach it to the issue you will create.

Regards

**Comment by NegroniBlast** [comment]
Hey guys, how do I know if the encoding fixes were included in later versions? I installed GLPI 10.0.12 and after connecting via 0auth i tried opening tickets via email with hebrew characters and I get gibberish instead.
![Uploading Screenshot 2024-07-01 at 14.07.51.png…]()

**Comment by NegroniBlast** [comment]
Hey guys, how do I know if the encoding fixes were included in later versions? I installed GLPI 10.0.12 and after connecting via 0auth i tried opening tickets via email with hebrew characters and I get gibberish instead.

![Screenshot 2024-07-01 at 14 07 51](https://github.com/glpi-project/glpi/assets/174329831/2ca35969-c5d7-4fe8-9845-fec60698872e)
