### ISSUE TITLE
[GLPI 9.5.1]  Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#7790]
Since 10am, I can't retrieve an email with the mailgate.
i dont know why i got this error message. It is no longer possible to retrieve messages.

php error logs :
[2020-07-30 12:00:05] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name subject or subject not found in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307
  Backtrace :
  ...r/laminas/laminas-mail/src/Storage/Part.php:376 Laminas\Mail\Storage\Part->getHeader()
  inc/mailcollector.class.php:1035                   Laminas\Mail\Storage\Part->__get()
  inc/mailcollector.class.php:734                    MailCollector->buildTicket()
  inc/mailcollector.class.php:1740                   MailCollector->collect()
  inc/crontask.class.php:847                         MailCollector::cronMailgate()
  front/crontask.form.php:49                         CronTask::launch()

[2020-07-30 12:04:37] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name subject or subject not found in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307
  Backtrace :
  ...r/laminas/laminas-mail/src/Storage/Part.php:376 Laminas\Mail\Storage\Part->getHeader()
  inc/mailcollector.class.php:1035                   Laminas\Mail\Storage\Part->__get()
  inc/mailcollector.class.php:734                    MailCollector->buildTicket()
  inc/mailcollector.class.php:1740                   MailCollector->collect()
  inc/crontask.class.php:847                         MailCollector::cronMailgate()
  front/crontask.form.php:49                         CronTask::launch()
  
  
[2020-07-30 12:11:18] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name subject or subject not found in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307
  Backtrace :
  ...r/laminas/laminas-mail/src/Storage/Part.php:376 Laminas\Mail\Storage\Part->getHeader()
  inc/mailcollector.class.php:1035                   Laminas\Mail\Storage\Part->__get()
  inc/mailcollector.class.php:734                    MailCollector->buildTicket()
  front/mailcollector.form.php:77                    MailCollector->collect()

my config
![Capture2](https://user-images.githubusercontent.com/68054991/88911247-dd9bfb00-d25d-11ea-9d51-e5080ee64a49.JPG)

error dans mailgate
![Capture](https://user-images.githubusercontent.com/68054991/88911262-e68ccc80-d25d-11ea-938c-6cd7522e6ed0.JPG)

**Comment by cedric-anne** [comment]
Hi,

Which version of GLPI are you using ?
It should have been fixed in 9.5.1.

Regards

**Comment by steph461** [comment]
GLPI 9.5.1 (/glpi => /var/www/html/glpi)
i had the bug this morning. And I have the 9.5.1

Mailgate retrieves messages, but not all messages.
I do not understand

![Capture](https://user-images.githubusercontent.com/68054991/88912411-839c3500-d25f-11ea-9254-931b6fe8a1a7.JPG)
version mailcollector

**Comment by steph461** [comment]
![Capture](https://user-images.githubusercontent.com/68054991/88912805-1fc63c00-d260-11ea-9853-1ec829de7bee.JPG)
If I run the task, I have a blank page

**Comment by steph461** [comment]
cron.log
2020-07-30 12:35:27 [7@srv-glpi]
Interne #1 : DÃ©marrage mailgate
=====================================
mailgate.log
2020-07-30 12:35:27 [7@srv-glpi]
Message invalide : Invalid header value detected<br/>
this bug I have for a while but I have not had a problem.
=======================================
php-errors.log
[2020-07-30 12:35:27] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name subject or subject not found in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307
  Backtrace :
  ...r/laminas/laminas-mail/src/Storage/Part.php:376 Laminas\Mail\Storage\Part->getHeader()
  inc/mailcollector.class.php:1035                   Laminas\Mail\Storage\Part->__get()
  inc/mailcollector.class.php:734                    MailCollector->buildTicket()
  inc/mailcollector.class.php:1740                   MailCollector->collect()
  inc/crontask.class.php:847                         MailCollector::cronMailgate()
  front/crontask.form.php:49                         CronTask::launch()

**Comment by steph461** [comment]
post #7619 unncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: **Header with Name reply-to or reply-**to not found in /var/www/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307

difference my log : 
Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: **Header with Name subject or subject not** found in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307

**Comment by cedric-anne** [comment]
#7748 should fix this.

Regards

**Comment by steph461** [comment]
its ok
bug résolve
thank you cedric-anne

**Comment by adamcios** [comment]
i still have this problem - version GLPI 9.5.7
[2022-02-10 00:09:11] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Header\Exception\InvalidArgumentException: Invalid header value detected in C:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Header\GenericHeader.php at line 64
  Backtrace :
  vendor\laminas\laminas-mail\src\Headers.php:544    Laminas\Mail\Header\GenericHeader::splitHeaderLine()
  vendor\laminas\laminas-mail\src\Headers.php:284    Laminas\Mail\Headers->loadHeader()
  vendor\laminas\laminas-mail\src\Headers.php:105    Laminas\Mail\Headers->addHeaderLine()
  vendor\laminas\laminas-mime\src\Decode.php:150     Laminas\Mail\Headers::fromString()
  ...r\laminas\laminas-mail\src\Storage\Part.php:111 Laminas\Mime\Decode::splitMessage()
  ...laminas\laminas-mail\src\Storage\Message.php:53 Laminas\Mail\Storage\Part->__construct()
  ...r\laminas\laminas-mail\src\Storage\Imap.php:127 Laminas\Mail\Storage\Message->__construct()
  ...aminas-mail\src\Storage\AbstractStorage.php:268 Laminas\Mail\Storage\Imap->getMessage()
  inc\mailcollector.class.php:721                    Laminas\Mail\Storage\AbstractStorage->current()
  inc\mailcollector.class.php:1762                   MailCollector->collect()
  inc\crontask.class.php:943                         MailCollector::cronMailgate()
  front\cron.php:83                                  CronTask::launch()

**Comment by cedric-anne** [comment]
@adamcios 

Please open a new issue, and attach the email that causes this issue. It may be due to another problem and, as the one tracked here seems to be solved, we will not try to investigate if we only have a contextless error trace.

Regards

**Comment by ftoledo** [comment]
@adamcios have you created a new issue? I also have the same in 9.5.7 with gmail accounts
@cedric-anne where can I put some log line to identify which message it is? to print the msgid or subject. Since I have several messages in the inbox and I can't identify which one triggers the problem. thanks!
