### ISSUE TITLE
9.5.1 IMAP connection with exchange 2013 not working

### ISSUE THREAD

**Issue by enannos** [glpi-project/glpi#7845]
GLPI Version 9.5.1

Hello everybody,

since the update to the latest 9.5.1, our connection with our Exchange is not working anymore.
We have kept the settings as they where, these are:
IMAP -> TLS
Port: 143
Folder: INBOX

These settings have worked for years, we didn't change anything into the Exchange configuration.

The apache logs(when I trigger a test connection) show:
 [php7:warn] [pid 23540] [client XXXXXXXXXXXXXX] PHP Warning:  stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php on line 106, referer: http://glpi.XXXX/front/mailcollector.form.php?id=2

php-errors.log

[2020-08-13 15:55:49] glpiphplog.WARNING:   *** PHP Warning (2): stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php at line 106
  Backtrace :
  .../laminas/laminas-mail/src/Protocol/Imap.php:106 stream_socket_enable_crypto()
  ...r/laminas/laminas-mail/src/Storage/Imap.php:216 Laminas\Mail\Protocol\Imap->connect()
  inc/toolbox.class.php:2324                         Laminas\Mail\Storage\Imap->__construct()
  inc/mailcollector.class.php:1314                   Toolbox::getMailServerStorageInstance()
  inc/mailcollector.class.php:686                    MailCollector->connect()
  front/mailcollector.form.php:77                    MailCollector->collect()

[2020-08-13 15:55:49] glpiphplog.ERROR: MailCollector::collect() in /var/www/html/glpi/inc/mailcollector.class.php line 692
An error occured trying to connect to collector. cannot enable TLS
 #0 /var/www/html/glpi/vendor/laminas/laminas-mail/src/Storage/Imap.php(216): Laminas\Mail\Protocol\Imap->connect('tXXXXXXXXXX...', '143', 'tls')
#1 /var/www/html/glpi/inc/toolbox.class.php(2324): Laminas\Mail\Storage\Imap->__construct(Object(stdClass))
#2 /var/www/html/glpi/inc/mailcollector.class.php(1314): Toolbox::getMailServerStorageInstance('imap', Array)
#3 /var/www/html/glpi/inc/mailcollector.class.php(686): MailCollector->connect()
#4 /var/www/html/glpi/front/mailcollector.form.php(77): MailCollector->collect('2', 1)
#5 {main}  {"user":"283@XXXXXXXX"}

**Comment by enannos** [comment]
Is there a possibility to revert to the old mailcollect function? 

Or is there a quick workaround on this issue?

Thanks

**Comment by trasher** [comment]
> The apache logs(when I trigger a test connection) show:
> [php7:warn] [pid 23540] [client XXXXXXXXXXXXXX] PHP Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php on line 106, referer: http://glpi.XXXX/front/mailcollector.form.php?id=2

This looks like a self-signed certificate issue. This was not supported in laminas-mail, see https://github.com/glpi-project/glpi/pull/7779.

Some other issues on collectors has been fixed since 9.5.1, you can try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)); but I guess this one is already fixed.

**Comment by enannos** [comment]
Hi Trasher,

just tried the nightly, it is still not working. 
Please do not close an issue if it has not been resolved!

**Comment by trasher** [comment]
> Please do not close an issue if it has not been resolved!
It's not very hard to reopen.

**Comment by ricardoamedeiros** [comment]
I'm having trouble logging into Exchange. The application connects, but gives a user and password error even without using special characters. The problem does not happen at office365. In version 9.4.6 the same configuration works. I have already changed the password several times and it was no use. I am not using TSL.

**Comment by cedric-anne** [comment]
> The apache logs(when I trigger a test connection) show:
> [php7:warn] [pid 23540] [client XXXXXXXXXXXXXX] PHP Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php on line 106, referer: http://glpi.XXXX/front/mailcollector.form.php?id=2

`error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed` is related to a problem during SSL negociation between GLPI and your mail server. This is not a GLPI issue, so we cannot

**Comment by cedric-anne** [comment]
Hi,

I am closing this issue as no feedback were given to latest comment.

Regards
