### ISSUE TITLE
 Error in mail message body encoding

### ISSUE THREAD

**Issue by SakisGalanis** [glpi-project/glpi#8008]
I just updated the GLPI to version 9.5.1 and all incoming emails from mailcollector are not displayed correctly in body. Characters are unreadable ( greek language ). In the previous version the characters were displayed correctly on both subject and body message. 
It is an on-premise installation ( apache 2.4, MySQL 5.7 on windows 2012 server

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)); there are already several issues that has been solved. Feel free to reopen if you can reproduce with last version.

**Comment by SakisGalanis** [comment]
Sorry for asking but i am newby in glpi and its installation. I downloaded the zipped file and extracted it. I am just replacing the current glpi folder with this one by disabling the plugins first and of course making a backup? Is it so simple?

**Comment by SakisGalanis** [comment]
I did the upgrade but the issue persists. Also the mail receiver is not working now!

**Comment by SakisGalanis** [comment]
I forgot to thank you for your reply...

**Comment by cedric-anne** [comment]
> I did the upgrade but the issue persists. Also the mail receiver is not working now!

Fixes done will fix only new tickets created from now.

Have you something in your logs related to the mail receiver ?

**Comment by SakisGalanis** [comment]
Thanks for your reply
I go to Setup -> Receivers -> Get Email Tickets Now and i get the following message: Invalid Email Address. An error occurred trying to connect to collector.last request failed
The address is correct and password is checked ( i am connecting to the Outloom  WebApp ) but no email is coming.

**Comment by cedric-anne** [comment]
Have you something in your logs related to the mail receiver ?

**Comment by SakisGalanis** [comment]
There are two files ( mail & mail-error ). I am attaching them.  
[mail-error.log](https://github.com/glpi-project/glpi/files/5297113/mail-error.log)
[mail.log](https://github.com/glpi-project/glpi/files/5297115/mail.log)

**Comment by cedric-anne** [comment]
This is related to sent emails, not to received ones.

Check in `php-errors.log`, `sql-errors.log`.

**Comment by SakisGalanis** [comment]
I am attaching the files. I cannot understand - as newby - the logs. Can you please help? I am sending the receiver's settimgs too

[sql-errors.log](https://github.com/glpi-project/glpi/files/5297235/sql-errors.log)

[php-errors.log](https://github.com/glpi-project/glpi/files/5297234/php-errors.log)
![Screenshot 2020-09-29 103857](https://user-images.githubusercontent.com/72032765/94527681-029df180-0240-11eb-8f83-b3bd595e9ce3.jpg)

**Comment by cedric-anne** [comment]
It seems that either your password is wrong, either the mail server refuses it. Can you try to type your password again in the password field of the receiver, and see i fproblem persist ? Can you also check that your connection is not being blocked by some security system on outlook side ?

**Comment by SakisGalanis** [comment]
I've changed the password and the settings and now it is working a bit strange. Some tickets arrive and some not. The receiver returns the error: Error in sending the email SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting but processes some tickets. 
Probably this is the reason why the followup is not working. I am answering to a ticket and the requester does not get the answer.

**Comment by cedric-anne** [comment]
These errors are related to SMTP settingin `Setup > Notifications > Email followups configuration`. You may had to reenter the smtp password to fix this.

**Comment by SakisGalanis** [comment]
I did it it know works and sends email. I am checking the way that followup is working

**Comment by SakisGalanis** [comment]
SMTP settings checked and a test email to administrator sent. I am replying to a task in followup tab and press close but no email send to requester. Is there anything else that I can check?

**Comment by cedric-anne** [comment]
Hi,

I guess this is due to notifications configuration. This has nothing to do with initial issue and does not seems to be a bug, so I close this issue.

You can ask for support on [community forum](https://forum.glpi-project.org) or get [professionnal support](https://glpi-project.org/subscriptions/).

Regards
