### ISSUE TITLE
Mail with accent in attachemment name not collected

### ISSUE THREAD

**Issue by Blank-Vcf** [glpi-project/glpi#8236]
Since update to glpi 9.5.2 some mail are not collected.
We have 5 collectors on the same mail server all are collected the same way with imap.

The common point of all mail not collected was the fact they all have some accent like éàç... in attachement name

Error in debug with glpi
![image](https://user-images.githubusercontent.com/16317786/98226942-fb60b680-1f56-11eb-9c26-ba566d90704e.png)

Error in mailgate.log:
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>2020-11-05 11:00:09 [@xxxxx]
Erreur lors de l'analyse du message : Invalid header value detected<br/>

mail in not collleted element:
![image](https://user-images.githubusercontent.com/16317786/98227439-a07b8f00-1f57-11eb-8b12-39645a1b7bee.png)

**Comment by stdglpi** [comment]
Hello @Blank-Vcf 

I had the same problem on "one" mail for the moment.

I don't know why, because the client answered on the discussion with a simple attachment.

I try to find the original email and find if there was an accent in the attachment name.

**Comment by Blank-Vcf** [comment]
i keep collected mail in subfolder in the mailbox and before glpi update i have somes mail with attachment with accent that have been collected.
And after update some mail with or without "correct attchement" are collected correctly.

**Comment by cedric-anne** [comment]
Hi,

Could you please export an email that triggers this issue into eml format and attach it here ? It would help us to debug.

Regards

**Comment by Blank-Vcf** [comment]
You have the eml + the attachement in the zip
mail send with nothing inside just the txt
[Desktop.zip](https://github.com/glpi-project/glpi/files/5508691/Desktop.zip)

**Comment by cedric-anne** [comment]
Hi,

Problem is same as #8148 and should be fixed by #8161 (but requires a patch on laminas-mail dependency as mentionned in #8161).

Regards

**Comment by Blank-Vcf** [comment]
I have updated src/Header/ContentDisposition.php only, test folder is not present in glpi ?
and inc/mailcollector.class.php but mail are still not collected.

**Comment by cedric-anne** [comment]
You have to also update laminas-mail dependency, as indicated in #8161

**Comment by Blank-Vcf** [comment]
made this one https://github.com/laminas/laminas-mail/pull/108/files/cafc1ac22f6576c42efce459d4fbcf1f3f37d636

**Comment by aagz** [comment]
> You have to also update laminas-mail dependency, as indicated in #8161

It doesn't work.

**Comment by trasher** [comment]
> > You have to also update laminas-mail dependency, as indicated in #8161
> 
> It doesn't work.

Maybe see https://github.com/glpi-project/glpi/issues/8495 or open a detailed new issue.
