### ISSUE TITLE
[9.5] - queuedmail, queuedmailclean and other actions dont work

### ISSUE THREAD

**Issue by moisesdfelix** [glpi-project/glpi#9420]
**Describe the bug**

After performing glpi updates from 9.1.1 to 9.5.5 the process for sending email notifications stopped

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

1. Go to 'settings'
2. Click on 'automatic actions'
3. Scroll down to 'queuedmail & queuedmailclean dont work'

**Expected behavior**

**Logs**

Função indefinida QueuedMail::cronqueuedmail (para cron)

Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**
![WhatsApp Image 2021-08-17 at 21 13 57](https://user-images.githubusercontent.com/50854086/129827613-bb837530-974c-4148-b553-5641e2814e65.jpeg)
![Screenshots 2021_5](https://user-images.githubusercontent.com/50854086/129827628-0bc02d4d-8870-41b0-88ac-a3fc092b8cd9.png)


If applicable, add screenshots to help explain your problem.


**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

the php version has been updated from 5.6 to 7.2

**Comment by cedric-anne** [comment]
Hi,

These tasks should have been renamed by the update process.

Either you restored your 9.1.1 backup onto the newly installe GLPI 9.5.5 database, either the update process failed at some point.

You should try to restore your 9.1.1 backup on an empty database, then run the update process again.

Regards

**Comment by moisesdfelix** [comment]
No. the updates were being done one by one until reaching 9.5.5.

**Comment by cedric-anne** [comment]
So it may have fail on some point.

Did you tried to update from 9.1.1 to 9.5.5 directly ?

**Comment by cedric-anne** [comment]
So, please, can you try to restore your backup and do the update from 9.1.1 to 9.5.5 directly ?

This data should have been udpated during migration from 9.1.x to 9.2.0, and maybe the first version of this migration was failing and has been fixed in a later version.

**Comment by moisesdfelix** [comment]
@cedric-anne Thank you for your help. I did a clean install with new database and the actions worked. however after restoring the database the problem remains.

I noticed that I disabled the action: "queuedmailclean" the actions work normally. 

Even running manually does not run. is there anything you can do with this job?

**Comment by cedric-anne** [comment]
> however after restoring the database the problem remains.

Did you restore your backup over a non empty database ?

**Comment by moisesdfelix** [comment]
Initially I did a restore to an empty database and it worked. 

Then I restored the old database and the actions did not run

**Comment by cedric-anne** [comment]
Upgrade process is simple, see https://glpi-install.readthedocs.io/en/latest/update.html .

Clearly, the error you have is due to the fact that you restored your GLPI backup over a non empty database (i.e your database was already containing another GLPI database).

I close this issue as it does not seems to be a bug (i.e. if there was a bug during migration from 9.1.x, it would have been reported and fixed years ago). To get support, you can ask for community support on [forum](https://forum.glpi-project.org/) or [get a subscription for a professionnal support](https://glpi-project.org/subscriptions/).

**Comment by moisesdfelix** [comment]
I cannot manually run the "queuedmail" and "queuedmail clean" services.

**Comment by cedric-anne** [comment]
> I cannot manually run the "queuedmail" and "queuedmail clean" services.

They have been renamed to `queuednotification` and `queuednotificationclean`.

**Comment by moisesdfelix** [comment]
update on the table glpi_crontasks

itemtype: QueuedMail => QueuedNotification
name : queuedmail => queuednotification
and :
itemtype : QueuedMail => QueuedNotification
name : queuedmailclean => queuednotificationclean

after updating the actions started to run but I can't receive the notification email. sending a test email by glpi i can receive normally.
